Validation date
scieloorg/packtools pull request #368
Opened 2023-02-06 21:00 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona funções para a validação da completude de data e da ordenação de datas em `history`.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
A partir dos casos de testes automatizados.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #365 e #366.

### Referências
NA.

2023-02-06 23:33 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +from packtools.sps.validation.values import CHRONOLOGICAL_ORDER_OF_EVENTS
@Rossi-Luciano CHRONOLOGICAL_ORDER_OF_EVENTS deve ser só parâmetro. Não criar constante.

2023-02-06 23:40 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +    def dates_are_sorted(self, order=CHRONOLOGICAL_ORDER_OF_EVENTS):
@Rossi-Luciano deixar sem valor padrão. Comentar a função com exemplos.
Use o padrão de comentário
https://pandas.pydata.org/docs/development/contributing_docstring.html

2023-02-06 23:54 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        return self.complete
A validação de completude das datas deve ser até o final. Imagina que você é um produtor de XML e por acaso há erro em todas as datas. O validador vai fornecer a mensagem até o primeiro erro. O ideal é fazer todas as validações possíveis. Então, o resultado deve ser uma lista de dicionários.

2023-02-07 00:10 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        return self.ordered
@Rossi-Luciano talvez a descrição não tenha ficado clara. Não é importante a ordem dos elementos no XML, mas sim o valor das datas. Em outras palavras, tem-se que validar a data dos eventos se estão na ordem cronológica correta, exemplos:

Dados:
EventoA - 2020/01/01
EventoB - 2023/01/02

#### Caso 1:
Ao atributo foi fornecido que a ordem cronológica é 'EventoB', 'EventoA'
O resultado é que está fora da ordem esperada

#### Caso 2:
Ao atributo foi fornecido que a ordem cronológica é 'EventoA', 'EventoB'
O resultado é que está na ordem esperada.

2023-02-07 00:14 UTC, robertatakenaka commented on packtools/sps/models/dates.py
> +    def history_dates(self):
@Rossi-Luciano para deixar o código da validação mais limpo, faça a seguinte alteração nesta classe:
- crie o atributo (property) history_dates_list, que simplesmente é a cópia deste atributo
- crie o atributo (property) history_dates_dict, em que a chave é o valor de `@date-type` e o valor é o mesmo dos itens da lista.

2023-02-07 00:41 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        return self.ordered
@Rossi-Luciano a lógica está corretíssima, mas o desempenho pode ser ruim. Implementando a recomendação: https://github.com/scieloorg/packtools/pull/368/files#r1098047487, este código pode ficar mais simples:

```python
# como este trecho vai ser usado repetidas vezes, pode-se criar uma função
def date_dict_to_date(date_dict):
    return date(int(date_dict['year']), int(date_dict['month']), int(date_dict['day']))

```

```python
def dates_are_sorted(self, order, required_events)
    seq = []
    history_dates = self.history.history_dates_dict
    for event_type in order:
        try:
            seq.append(date_dict_to_date(history_dates[event_type]))
        except KeyError:
            # ok, pode ser uma data não obrigatória
            # talvez nesta função podemos incluir um novo parâmetro que informa
            # as datas obrigatórias
            if event_type in required_events:
                # anotar erro
                ...
            else:
                pass
    # montar o retorno se sucesso ou se falha
    if seq == sorted(seq):
        
        ...
```

2023-02-07 00:42 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        return self.ordered
@Rossi-Luciano Procure na mensagem de retorno, informar a entrada, a saída obtida, e a saída esperada. Isso ajuda o usuário a corrigir os defeitos do XML.

2023-02-07 00:44 UTC, robertatakenaka requested changes
@Rossi-Luciano adicionar as recomendações

2023-02-07 22:42 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            'input': {
@Rossi-Luciano considere também como "input" as datas e seus tipos, pois são os objetos de validação.

2023-02-07 22:45 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        if seq == sorted(seq) and len(seq) == len(order):
@Rossi-Luciano qual é a necessidade de `len(seq) == len(order)`? Se existe, pode fazer um teste em que `len(seq) != len(order)`?

2023-02-07 22:52 UTC, robertatakenaka commented on packtools/sps/models/dates.py
> +            _dates[event_date['type']] = {'year': event_date['year'], 'month': event_date['month'], 'day': event_date['day']}
@Rossi-Luciano basta assim:
```
_dates[event_date['type']] = event_date
```
Você pode dizer: "Ah, mas aí o type permanece". Não há problema nisso. O importante é conseguir obter os dados acessando pela chave.

2023-02-07 22:55 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        self.ordered = None
@Rossi-Luciano não faz sentido ter este atributo, pois esta classe estaria validando todas as datas dos artigos.
Algumas datas de artigos não são completas por natureza. Algumas só tem ano, outras só mês e ano.
E a ordenação, pode até fazer sentido.

2023-02-07 22:58 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                self.complete = False
@Rossi-Luciano adicione ao dicionário `response` o valor de `complete`

2023-02-07 23:04 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                self.complete = False
@Rossi-Luciano 
1. mude o nome da função de `dates_are_complete` para `history_dates_are_complete`
2. Cada item verificado deve resultar em um dicionário. Sempre com padrão de input, output, se houve ou não erro.

2023-02-08 17:09 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +from packtools.sps.validation.values import CHRONOLOGICAL_ORDER_OF_EVENTS
@robertatakenaka a constante foi removida.

2023-02-08 17:10 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +    def dates_are_sorted(self, order=CHRONOLOGICAL_ORDER_OF_EVENTS):
@robertatakenaka, os exemplos foram adicionados.

2023-02-08 17:11 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +        return self.complete
@robertatakenaka, o código foi modificado para considerar as datas individualmente, resultando em um dicionário.

2023-02-08 17:11 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +        return self.ordered
@robertatakenaka, as melhorias foram implementadas.

2023-02-08 17:11 UTC, Rossi-Luciano commented on packtools/sps/models/dates.py
> +    def history_dates(self):
@robertatakenaka, os atributos foram criados.

2023-02-08 17:12 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            'input': {
@robertatakenaka, o 'input' foi complementado.

2023-02-08 17:13 UTC, Rossi-Luciano commented on packtools/sps/models/dates.py
> +            _dates[event_date['type']] = {'year': event_date['year'], 'month': event_date['month'], 'day': event_date['day']}
@robertatakenaka, feito.

2023-02-08 17:13 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +        self.ordered = None
@robertatakenaka, os atributos foram removidos.

2023-02-08 17:14 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +                self.complete = False
@robertatakenaka, o nome da função foi alterado.

2023-02-09 01:09 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                'events_date': [{key: date_dict_to_date(value)} for key, value in history_dates.items()]
@Rossi-Luciano No lugar de `[{key: date_dict_to_date(value)} for key, value in history_dates.items()]`, use o conteúdo de `self.history.history_dates_dict` ou `self.history.history_dates_list`, ou seja:

```python
                'events_date': history_dates
```

2023-02-09 01:12 UTC, robertatakenaka approved these changes
Estou aprovando, mas em uma próxima oportunidade, faça a melhoria solicitada. Isso implicará em alterar os testes.

2023-02-09 01:14 UTC, merged