Jornal meta validation
scieloorg/packtools pull request #370
Opened 2023-02-09 17:31 UTC by Rossi-Luciano

#### O que esse PR faz?
Cria classes de validação, com os respectivos teste automatizados, para os valores de `Journal_Meta`.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Por meio do seguinte comando: `python3 -m unittest -v -k test_journal_meta`.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #369.

### Referências
NA.

2023-02-09 17:44 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +            attrib='issn_epub',
@Rossi-Luciano O usuário produtor de XML enxerga apenas o XML e não os atributos das classes. As mensagens são para os produtores de XML. Então, você pode indicar como input, o dado apresentado no XML, por exemplo:

```xml
<issn pub-type="epub">1980-850X</issn>
```
Sendo assim, não faz sentido `attrib='issn_epub'`, nem `input=self.xmltree,`
Então, use, por exemplo: `input='<issn pub-type="epub">1980-850X</issn>'`.
Para os demais atributos de response, OK.

2023-02-09 21:02 UTC, robertatakenaka requested changes
Ver o comentário sobre a identificação do objeto / dado a ser validado.

2023-02-10 11:36 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +            attrib='issn_epub',
OK, @robertatakenaka.

2023-02-10 15:04 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +            output_obteined=self.journal_issns.epub,
@Rossi-Luciano na verdade, os nomes mais adequado são `expected_value` e `provided_value` no lugar de output_expected e output_obteined

2023-02-10 15:09 UTC, robertatakenaka commented on tests/sps/validation/test_journal_meta.py
> +        )
@Rossi-Luciano Nos testes, evite usar variáveis ao definir o resultado esperado, pois pode haver erro  de código, então é mais garantido, claro e explícito, usar:

```python
expected = {
    "object": "issn epub",
    "expected_value": "1678-4790",
    "provided_value": "1678-4790",
    "match": True,
}
```

2023-02-10 15:10 UTC, robertatakenaka commented on tests/sps/validation/test_journal_meta.py
> +        )
@Rossi-Luciano copie o código 

```python
dict(
            object='issn epub',
            output_expected='1678-4790',
            output_obteined='1678-4790',
            match=True
        )

```
e cole no terminal do python para obter o resultado esperado

2023-02-10 15:12 UTC, robertatakenaka approved these changes
@Rossi-Luciano Vou aprovar, mas por favor, faça as melhorias em uma próxima oportunidade

2023-02-10 15:13 UTC, merged