Article xref
scieloorg/packtools pull request #378
Opened 2023-02-16 14:56 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona classes para validação de elementos com referências cruzadas.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/test_article_xref.py` e `python3 -m unittest -v tests/sps/validation/test_article_xref.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #371

### Referências
NA.

2023-02-16 19:37 UTC, robertatakenaka commented on packtools/sps/models/article_xref.py
> +        return self.all_xref_rids - self.all_ids
@Rossi-Luciano isso deve ficar na classe de validação

2023-02-16 19:38 UTC, robertatakenaka commented on packtools/sps/validation/article_xref.py
> +    def validate_citing_elements(self, expected_value):
@Rossi-Luciano o valor esperado já está contido no próprio de modo que não há necessidade de usar parâmetros.

2023-02-16 19:40 UTC, robertatakenaka commented on packtools/sps/validation/article_xref.py
> +        return resp
mesmos comentários anteriores

2023-02-16 19:48 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +class ArticleXrefTest(TestCase):
Deveria se chamar `ArticleXrefValidationTest`

2023-02-16 19:52 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +
Ou vc cria uma classe para cada XML (ok,  xref ausentes, elementos ausentes, nenhum xref e nenhum elemento)
Ou vc instancia cada teste com um XML que representa cada um destes casos.
Lembrando que o próprio XML contém o valor esperado de rids e ids, não faz sentido passar os valores esperados por parâmetro, isso não é a situação real.

2023-02-16 19:54 UTC, robertatakenaka requested changes
Verificar comentários e fazer correções

2023-02-21 21:44 UTC, Rossi-Luciano commented on packtools/sps/models/article_xref.py
> +        return self.all_xref_rids - self.all_ids
OK @robertatakenaka, os atributos foram movidos.

2023-02-21 21:45 UTC, Rossi-Luciano commented on packtools/sps/validation/article_xref.py
> +    def validate_citing_elements(self, expected_value):
Podemos conversar sobre isso? Acho que não entendi.

2023-02-21 21:45 UTC, Rossi-Luciano commented on packtools/sps/validation/article_xref.py
> +            output_obteined=self.article_xref.all_ids,
OK.

2023-02-21 21:45 UTC, Rossi-Luciano commented on packtools/sps/validation/article_xref.py
> +        return resp
OK.

2023-02-21 21:45 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_xref.py
> +class ArticleXrefTest(TestCase):
OK.

2023-02-21 21:46 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_xref.py
> +
Podemos conversar sobre isso? Acho que não entendi.

2023-02-24 12:57 UTC, Rossi-Luciano commented on packtools/sps/models/article_xref.py
> +        return self.all_xref_rids - self.all_ids
@robertatakenaka corrigido conforme orientado

2023-02-24 12:58 UTC, Rossi-Luciano commented on packtools/sps/validation/article_xref.py
> +    def validate_citing_elements(self, expected_value):
@robertatakenaka corrigido conforme orientado

2023-02-24 12:58 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_xref.py
> +
@robertatakenaka corrigido conforme orientado

2023-02-24 14:49 UTC, robertatakenaka commented on packtools/sps/validation/article_xref.py
> +class ArticleXrefValidation:
@Rossi-Luciano está difícil de ler o código por conta dos termos "citing" e "cited". Será mais difícil ainda para quem não tem conhecimento dos termos.
Por favor, mude para "ids" e "rids" pois acho que vai ficar mais legível.
Lembrando que os usuários que vão ver as mensagens conhecem o XML, então é muito mais fácil de compreender mensagens que contenham os nomes dos elementos e atributos de XML. Quando se refere de `aff1` é do `@id` ou do `@rid`?

2023-02-24 15:25 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +                    <p>citing element<xref ref-type="aff" rid="aff1">1</xref></p>
@Rossi-Luciano aqui é o elemento citado, pois é a afiliação "aff1" está sendo mencionada. Não use os termos cited e citing, pois dá confusão.

2023-02-24 15:26 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +                    </fig>
aqui não é a figura citada. É a figura em si.

2023-02-24 15:32 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +            msg="ERROR: the citing elements {'table1'} do not have the respective cited elements"
A mensagem deveria conter o nome do elemento ou do atributo e não os termos "citing" e "cited". O produtor de XML não tem este vocabulário.
A mensagem mais amigável é:

> Foi encontrado `xref[@rid='table1']` mas não foi encontrado `table-wrap[@id='table1']`

Em outras palavras:

> Foi encontrado elemento xref com atributo id com valor table1, mas não foi encontrado o elemento correspondente com o atributo id com valor table1

Como mensagem de recomendação é:

> Verifique se o valor table1 está correto ou se faltou identificar o elemento cujo atributo id é table1

2023-02-24 15:35 UTC, robertatakenaka requested changes
Revisar os comentários.
A lógica está correta, mas o código está difícil de ler devido aos termos cited e citing.
As mensagens precisam levar em conta o vocabulário do produtor de XML: id e rid. Não usar os termos citing e cited.

2023-02-24 18:32 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +            cited_elements={'aff1', 'fig1', 'table1'},
Pode usar 'expected_value' e 'obtained_value'. Lembre-se de manter um padrão na resposta, senão ficará difícil de montar um relatório se há muita variedade nas chaves dos dicionários.

2023-02-27 00:31 UTC, Rossi-Luciano commented on packtools/sps/validation/article_xref.py
> +class ArticleXrefValidation:
OK, @robertatakenaka.

2023-02-27 00:31 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_xref.py
> +                    <p>citing element<xref ref-type="aff" rid="aff1">1</xref></p>
OK, @robertatakenaka.

2023-02-27 13:07 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +                f"{self.article_xref.validate_rid()['expected_value']} but there were "
**Não** use variáveis para definir o valor esperado do teste.
Troque `f"{self.article_xref.validate_rid()['expected_value']}` por `['aff1', 'fig1']`

2023-02-27 13:07 UTC, robertatakenaka commented on tests/sps/validation/test_article_xref.py
> +                f"{self.article_xref.validate_id()['expected_value']} but there were "
Mesmo comentário anterior

2023-02-27 13:08 UTC, robertatakenaka approved these changes

2023-02-27 13:08 UTC, merged