Cria classe de extracao e teste relacionados aos dados de afiliacao
scieloorg/packtools pull request #396
Opened 2023-03-17 14:46 UTC by samuelveigarangel

#### O que esse PR faz?
Cria classe de extração e teste relacionados ao dados de afiliação 

#### Onde a revisão poderia começar?
Pelo commit.

#### Como este poderia ser testado manualmente?
`python setup.py test -s tests/sps/test_aff.py`

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
[#382](https://github.com/scieloorg/packtools/issues/382)

### Referências
N/A

2023-03-20 11:24 UTC, gitnnolabs commented
@scieloorg/scielo-ps-developers 

Validando esse PR.

2023-03-21 20:09 UTC, gitnnolabs requested changes

2023-03-21 20:09 UTC, gitnnolabs commented on packtools/sps/models/aff.py
> +                try:
@samuelveigarangel 

O que acha de criar uma lista com ["orgname", "orgdiv1", "orgdiv2", "original"] e realizar essa avalição de índice dentro de um laço?

2023-03-22 11:56 UTC, samuelveigarangel commented on packtools/sps/models/aff.py
> +                try:
Acho que é uma solução válida, deixaria o código mais dinâmico caso aparecesse outro dado relacionado a instituição, que não é caso. Por outro lado, a abordagem atual do código é mais explícita e fácil de entender para quem estiver lendo. Portanto, para garantir a clareza e legibilidade do código, talvez seja mais indicado manter a forma como está implementado.

2023-03-22 12:07 UTC, gitnnolabs commented on packtools/sps/models/aff.py
> +                try:
Discordo, não há dificuldade em ler um laço no código. 

Nessa repetição de código estamos quebrando um principio basal do DRY, veja: https://awari.com.br/solid-kiss-dry-yagni/?utm_source=blog

Resumidamente o **DRY** defini exatamente o contrário do seu argumento: 

**Ele prega que todo programador deve reduzir ao máximo a repetição de informações ou métodos, e com isso evitar redundâncias.** 

**Duplicação é desperdício**

Cada linha de código que entra em um aplicativo, e é mantida, se torna uma fonte potencial de bugs futuros. Isso porque, dentre outros fatores, a duplicação “incha” a base de código desnecessariamente, resultando em mais oportunidades para bugs, além de adicionar complexidade acidental ao sistema. 

O programador que aprende a reconhecer a duplicação e entende como eliminá-la é capaz de produzir um código muito mais limpo. Sendo assim, é recomendável, por exemplo, dividir o código em segmentos menores para conseguir gerenciá-lo e utilizar um único segmento em qualquer ponto, chamando-o sempre que necessário.

O princípio DRY garante que qualquer modificação de um único elemento de um sistema não requer uma mudança em outros elementos logicamente não relacionados. Além disso, elementos logicamente relacionados mudam de maneira previsível e uniforme, o que os mantém sincronizados.

2023-03-22 12:08 UTC, gitnnolabs requested changes
@samuelveigarangel por gentileza, realize as alterações solicitadas.

2023-03-24 12:37 UTC, merged