Issue 387
scieloorg/packtools pull request #402
Opened 2023-04-18 12:30 UTC by samuelveigarangel

#### O que esse PR faz?
Cria Função que chama os métodos de validação da classe de validação

#### Onde a revisão poderia começar?
pelo commit

#### Como este poderia ser testado manualmente?
`python -m packtools.report --arg1 'caminho do arquivo xml' `

Por exemplo:
`python -m packtools.report --arg1 'tests/samples/0034-7094-rba-69-03-0227.xml'`

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
[https://github.com/scieloorg/packtools/issues/387](#387)

### Referências
N/A

2023-04-19 12:34 UTC, robertatakenaka commented on packtools/sps/validation/article_authors.py
> +        from tests.sps.validation.test_article_authors import credit_terms_and_urls
@samuelveigarangel acho que não deveria importar módulos de testes

2023-04-19 12:36 UTC, robertatakenaka commented on packtools/sps/validation/article_authors.py
> +        from tests.sps.validation.test_article_authors import credit_terms_and_urls
O que pensei para a função seria:

```python
def validate(self, data):
    items = self.validate_authors_role(data['credit_terms_and_urls'])
    items += self.validate_authors_orcid()
    return items
```
Supondo que `self.validate_authors_role(data['credit_terms_and_urls'])` e `self.validate_authors_orcid()` estejam retornando lista de dicionários.

2023-04-19 12:38 UTC, robertatakenaka commented on packtools/sps/validation/article_authors.py
> +            'authors_role_validation':
Acho desnecessário a chave, pois no resultado de `self.validate_authors_role(data['credit_terms_and_urls'])` e `self.validate_authors_orcid()`, teríamos menção àquilo que está sendo validado.

2023-04-19 12:41 UTC, robertatakenaka commented on packtools/report.py
> +    def report(self):
adiciona o parâmetro data: `def report(self, data):`

2023-04-19 12:42 UTC, robertatakenaka commented on packtools/report.py
> +            report.append(cla(self.xmltree).call_methods)
Troca `.call_methods`, por `.validate(data)`

2023-04-19 12:43 UTC, robertatakenaka requested changes
Verificar os comentários

2023-04-19 12:46 UTC, robertatakenaka commented on packtools/report.py
> +    ]
Muito bem!

2023-04-19 12:48 UTC, robertatakenaka commented on packtools/report.py
> +        self.file_path = file_path
poderia adicionar o caminho para um arquivo de saída

2023-04-19 12:48 UTC, robertatakenaka commented on packtools/report.py
> +        self.file_path = file_path
poderia adicionar um atributo para gravar o arquivo de saída

2023-04-19 12:49 UTC, robertatakenaka commented on packtools/report.py
> +        report = []
poderia usar `yield` no lugar de acumular o resultado em lista

2023-04-19 13:09 UTC, samuelveigarangel commented on packtools/sps/validation/article_authors.py
> +            'authors_role_validation':
Ao adicionar a chave, ficaria mais fácil organizar na tela de validação e para o usuário ter uma visão melhor do que está sendo validado. Assim, no wagtail, eu imagino que poderia separar por "categoria"

2023-04-19 15:07 UTC, robertatakenaka commented on packtools/sps/validation/article_authors.py
> +            'authors_role_validation':
@samuelveigarangel entendo seu ponto. Mas que tal o seguinte:
No resultado de `validate()` retorne um iterável. Na função cliente você adiciona as chaves.
A vantagem desta abordagem é que o resultado é um iterável que pode ser usado para gerar um jsonl.

2023-04-19 15:12 UTC, robertatakenaka commented on packtools/sps/validation/article_authors.py
> +            'authors_role_validation':
@samuelveigarangel enfim, acho que pode manter assim, mas cuidado com os nomes das chaves, pois a função não valida somente `role`

2023-04-21 10:19 UTC, robertatakenaka commented on packtools/sps/validation/article_license.py
> +                self.validate_license_code(data['expected_code'], data['expected_version'])
expected_license_code
expected_license_version

2023-04-21 10:20 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            data['order'],
qualificar order (ordem de que?)

2023-04-21 10:20 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            data['order'],
history_dates_required_order

2023-04-21 10:23 UTC, robertatakenaka commented on tests/test_validation_report.py
> +            'expected_version': 'by',
O expected_code e expected_version são aquilo que está presente no link. Me parece que o link está redundante.

2023-04-21 10:25 UTC, robertatakenaka commented on packtools/validation_report.py
> +from tests.sps.validation.test_article_authors import credit_terms_and_urls
não se importa módulos de testes.
Se este módulo é usado em testes e na aplicação.
Então, faça-o ser um módulo da aplicação.

2023-04-21 10:27 UTC, robertatakenaka commented on packtools/validation_report.py
> +from tests.sps.validation.test_article_authors import credit_terms_and_urls
No entanto, isso deveria ser uma variável informada assim como `data`

2023-04-21 10:29 UTC, robertatakenaka commented on packtools/validation_report.py
> +            data_file_path = 'data_validation.json'
Isso substitui as duas linhas
```python
data_file_path = data_file_path or 'data_validation.json'
```

2023-04-21 10:31 UTC, robertatakenaka commented on packtools/validation_report.py
> +                f.write(",\n".join(data))
você poderia trocar isso incluindo um for  com tratamento de exceção de modo que ficará evidente onde está o problema de codificação para JSON

2023-04-21 10:32 UTC, robertatakenaka commented on packtools/validation_report.py
> +            LOGGER.info('Decoding JSON has failed')
Em caso, de leitura, também poderia adotar o for, considerando que é um jsonl, leitura linha a linha. Facilita identificar onde ocorre o erro de decodificação.

2023-04-21 10:34 UTC, robertatakenaka commented on packtools/validation_report.py
> +            LOGGER.info('Decoding JSON has failed')
Evite mensagem padrão `'Decoding JSON has failed'`. Isso não quer dizer nada. Melhora se pegar a mensagem
```python
except json.decoder.JSONDecodeError as exc:  # inclui json.decoder.JSONDecodeError
            LOGGER.info(f'Decoding JSON has failed {exc}')
```

2023-04-21 10:35 UTC, robertatakenaka commented on packtools/validation_report.py
> +    parser.add_argument("--arg1", type=str, help="The path to the XML file.")
trocar os nomes: arg1 por xml_file_path e arg2 por validation_criteria

2023-04-21 10:37 UTC, robertatakenaka commented on data_validation.json
> +{
Renomeia este arquivo como `validation_criteria_example.json`.

2023-04-21 10:41 UTC, robertatakenaka commented on tests/test_validation_report.py
> +        for expected, result in zip(expected_result, list(result_generator)):
Suspeito que não é necessário converter result_generator em lista

2023-04-25 16:43 UTC, robertatakenaka commented on packtools/sps/validation/front_articlemeta_issue.py
> +        vol_results.update(suppl_results)
melhores opções, sendo a 1 a melhor.
1.
```python
results = {
            'article_volume_validation': self.validate_volume(data['expected_value_volume']),
            'article_issue_validation': self.validate_issue(data['expected_value_issue']),
            'article_supplement_validation': self.validate_supplement(data['expected_value_supplment']),
        }
```
2.
```python
results = {}
results['article_volume_validation'] = self.validate_volume(data['expected_value_volume'])
results['article_issue_validation'] = self.validate_issue(data['expected_value_issue'])
results['article_supplement_validation'] = self.validate_supplement(data['expected_value_supplment'])
```

2023-04-25 16:45 UTC, robertatakenaka approved these changes
@samuelveigarangel anotei umas melhorias que você pode fazer futuramente em algum momento oportuno

2023-04-25 16:45 UTC, merged