Pubmed part 2
scieloorg/packtools pull request #429
Opened 2023-06-15 19:28 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona funções para tratar arquivos XML no padrão SciELO e representa-los em arquvos XML no padrão PudMed.

#### Onde a revisão poderia começar?
Por commit.

#### Como este poderia ser testado manualmente?
Avaliar os testes.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #417 
TK #418 
TK #419 

### Referências
NA.

2023-06-19 18:45 UTC, robertatakenaka reviewed
@Rossi-Luciano Para os TODO, consutar os XML SciELO e encontrar a correspondência no XML PubMed. Há elementos que claramente tem correspondência.

2023-06-19 18:47 UTC, robertatakenaka commented on packtools/sps/formats/pubmed.py
> +            # Season
@Rossi-Luciano Procure exemplos de season nos periódicos da área de Saúde aqueles que não publicam mensalmente

2023-07-04 13:42 UTC, robertatakenaka commented on packtools/sps/models/aff.py
>                  affiliation_id = aff_node.get('id', '')
@Rossi-Luciano eu particularmente prefiro None que string vazio, pois acredito que tem significado distintos. None é ausência, string vazia é um valor presente. Então, daria preferência a None. Ou seja, deveria ficar:
```python

affiliation_id = aff_node.get('id')
```

2023-07-04 13:42 UTC, robertatakenaka commented on packtools/sps/models/aff.py
>                      label = ''
`label = None`

2023-07-04 13:42 UTC, robertatakenaka commented on packtools/sps/models/aff.py
>                          address[field] = ''
pass no lugar de `address[field] = ''`

2023-07-04 13:50 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
>  def get_main_author(node):
Esta função, na verdade, deveria chamar a que pegar todos os autores e retornar o primeiro item. Sendo assim, acho que ela é desnecessária

2023-07-04 13:51 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +    return None if not ids else ids
Troca por apenas `return ids`

2023-07-04 13:52 UTC, robertatakenaka requested changes
Verificar os comentários e realizar as correções

2023-07-21 15:35 UTC, Rossi-Luciano commented on packtools/sps/models/aff.py
>                  affiliation_id = aff_node.get('id', '')
Ok, @robertatakenaka corrigido.

2023-07-21 15:35 UTC, Rossi-Luciano commented on packtools/sps/models/aff.py
>                      label = ''
Ok, @robertatakenaka corrigido.

2023-07-21 15:43 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
>  def get_main_author(node):
@robertatakenaka, o conteúdo da função foir removido e no lugar foi inserido o seguinte:

```
def get_main_author(node):
    return get_all_authors(node)[0]
```

Achei mais semântico manter a função, mas podemos remove-la se achar melhor.

2023-07-21 15:43 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +    return None if not ids else ids
Ok, @robertatakenaka corrigido.

2023-07-21 16:26 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
>  def get_main_author(node):
Perfeito!

2023-07-21 16:27 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
>              d['surname'] = author.find('surname').text
Alternativamente, pode-se usar `author.findtext('surname')`, que não levanta exceção e retorna `None` caso ausente `surname`.

2023-07-21 16:35 UTC, robertatakenaka commented on packtools/sps/formats/pubmed.py
> +            # TODO
@Rossi-Luciano não existe exemplo, mas existe as tags na JATS (suffix)

2023-07-21 16:35 UTC, robertatakenaka commented on packtools/sps/formats/pubmed.py
> +            # TODO
@Rossi-Luciano na JATS é collab

2023-07-21 16:42 UTC, robertatakenaka approved these changes

2023-07-21 16:42 UTC, merged