Article ref list
scieloorg/packtools pull request #430
Opened 2023-06-19 18:29 UTC by Rossi-Luciano

#### O que esse PR faz?
Refatora os métodos de extração de dados de citações (referências).

#### Onde a revisão poderia começar?
Por commit.

#### Como este poderia ser testado manualmente?
A partir da avaliação dos testes.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #422 

### Referências
NA.

2023-06-19 18:36 UTC, robertatakenaka commented on tests/sps/test_article_citations.py
> +                'all_authors': ['Tran B', 'Falster MO', 'Douglas K', 'Blyth F', 'Jorm LR'],
@Rossi-Luciano manter given-names e surnames. Evite alterar o conteúdo.

2023-06-19 18:37 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +            result.append(" ".join([surname.text, given_name.text]))
@Rossi-Luciano não mude o conteúdo, preserve o original

2023-06-19 18:37 UTC, robertatakenaka requested changes
Veja os comentários

2023-06-22 11:50 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +            result.append(" ".join([surname.text, given_name.text]))
OK, @robertatakenaka

2023-06-22 12:33 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +            'surname': author.find('surname').text,
@Rossi-Luciano verificar se existe suffix na JATS para os autores de referências bibliográfics

2023-06-22 12:34 UTC, robertatakenaka approved these changes

2023-06-22 12:34 UTC, merged