Xml converter
scieloorg/packtools pull request #442
Opened 2023-07-20 02:59 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona:
- geradores para os formatos: CROSSREF, PUBMED e PMC;
- conversor (parcial) do formato JATS para PMC;
- ajustes gerais.

#### Onde a revisão poderia começar?
Por commit.

#### Como este poderia ser testado manualmente?
Avaliar os testes.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TKs #434 e #436 

### Referências
NA.

2023-07-20 12:50 UTC, robertatakenaka commented on packtools/sps/formats/crossref_generator.py
> +    parser.add_argument('-o', '--path to xml file in crossref format', action='store', dest='path_to_write', required=True,
@Rossi-Luciano os nomes dos parâmetros não podem conter espaços:
Trocar `depositor email address` por `depositor_email_address` e assim por diante

2023-07-20 12:52 UTC, robertatakenaka commented on packtools/sps/formats/pmc_generator.py
> +                        help='Path for writing the CrossRef XML file.')
melhore os nomes dos parâmetros, deixe-os mais curtos e simples
scielo_xml e pubmed_xml

2023-07-20 12:53 UTC, robertatakenaka commented on packtools/sps/formats/pmc_generator.py
> +                        help='Path for writing the CrossRef XML file.')
Revise o texto de help (CrossRef???)

2023-07-20 12:54 UTC, robertatakenaka commented on packtools/sps/formats/pubmed_generator.py
> +    parser = argparse.ArgumentParser(description='Convert XML file in SciELO format to Pubmed format.')
Troque `in` por `from`

2023-07-20 12:56 UTC, robertatakenaka commented on packtools/sps/formats/pubmed_generator.py
> +        file.write(xml_crossref_formated)
crossref ou pubmed?

2023-07-20 12:57 UTC, robertatakenaka requested changes
Verificar os comentários e fazer as correções

2023-07-20 13:17 UTC, Rossi-Luciano commented on packtools/sps/formats/crossref_generator.py
> +    parser.add_argument('-o', '--path to xml file in crossref format', action='store', dest='path_to_write', required=True,
Ok @robertatakenaka, corrigido.

2023-07-20 13:17 UTC, Rossi-Luciano commented on packtools/sps/formats/pmc_generator.py
> +                        help='Path for writing the CrossRef XML file.')
Ok @robertatakenaka, corrigido.

2023-07-20 13:20 UTC, Rossi-Luciano commented on packtools/sps/formats/pubmed_generator.py
> +    parser = argparse.ArgumentParser(description='Convert XML file in SciELO format to Pubmed format.')
Ok @robertatakenaka, corrigido.

2023-07-20 13:20 UTC, Rossi-Luciano commented on packtools/sps/formats/pubmed_generator.py
> +                        help='Path for writing the CrossRef XML file.')
Ok @robertatakenaka, corrigido.

2023-07-20 13:20 UTC, Rossi-Luciano commented on packtools/sps/formats/pubmed_generator.py
> +        file.write(xml_crossref_formated)
Ok @robertatakenaka, corrigido.

2023-07-24 18:38 UTC, robertatakenaka commented on packtools/sps/formats/crossref.py
>  def create_author(item, citation):
@Rossi-Luciano Adicionar comentários no estilo https://pandas.pydata.org/docs/development/contributing_docstring.html

2023-07-24 18:40 UTC, robertatakenaka commented on packtools/sps/formats/pmc.py
> +def xml_pmc_authors(xml_tree):
@Rossi-Luciano adicionar comentários no padrão https://pandas.pydata.org/docs/development/contributing_docstring.html

2023-07-24 18:41 UTC, robertatakenaka commented on packtools/sps/formats/pmc.py
> +    affs = xml_tree.findall(".//aff")
@Rossi-Luciano adicionar comentários
https://pandas.pydata.org/docs/development/contributing_docstring.html

2023-07-24 18:43 UTC, robertatakenaka commented on packtools/sps/formats/pmc_generator.py
> +
@Rossi-Luciano adiciona mensagem "Arquivo criado em: local..."

2023-07-24 18:44 UTC, robertatakenaka commented on packtools/sps/formats/pubmed_generator.py
> +
@Rossi-Luciano adiciona mensagem "Arquivo criado em: local..."

2023-07-24 18:45 UTC, robertatakenaka commented on tests/sps/test_article_abstract.py
> +        print(data)
@Rossi-Luciano remove `print()`

2023-07-24 18:51 UTC, robertatakenaka commented on packtools/sps/formats/pmc.py
> +            aff.text = aff_institution
@Rossi-Luciano a existência de `aff/label` (`<label>...</label>`) está vinculada à existência de `<xref ref-type="aff">...</xref>` no respectivo autor.

2023-07-24 18:52 UTC, robertatakenaka commented on packtools/sps/formats/pmc.py
> +            aff.text = aff_institution
@Rossi-Luciano elaborar casos de testes  contrib com e sem xref, label criado ou não em aff

2023-07-24 18:53 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar a questão de aff e xref em PMC

2023-07-27 20:58 UTC, Rossi-Luciano commented on packtools/sps/formats/crossref.py
>  def create_author(item, citation):
OK @robertatakenaka

2023-07-27 20:59 UTC, Rossi-Luciano commented on packtools/sps/formats/pmc.py
> +def xml_pmc_authors(xml_tree):
Ok @robertatakenaka

2023-07-28 18:44 UTC, Rossi-Luciano commented on packtools/sps/formats/pmc_generator.py
> +
OK @robertatakenaka

2023-07-28 18:44 UTC, Rossi-Luciano commented on packtools/sps/formats/pubmed_generator.py
> +
OK @robertatakenaka

2023-07-28 18:44 UTC, Rossi-Luciano commented on packtools/sps/formats/crossref_generator.py
> +
OK @robertatakenaka

2023-07-28 18:44 UTC, Rossi-Luciano commented on packtools/sps/formats/pmc.py
> +            aff.text = aff_institution
OK @robertatakenaka

2023-07-31 19:36 UTC, robertatakenaka commented on packtools/sps/formats/crossref.py
> +    """
@Rossi-Luciano este comentário deveria ser da função que chama create_issue

2023-07-31 19:37 UTC, robertatakenaka commented on packtools/sps/formats/crossref.py
> +    """
E no lugar de  `def create_issue(item, citation):` usar `def create_issue(item, issue):`

2023-07-31 19:40 UTC, robertatakenaka commented on packtools/sps/formats/crossref.py
> +        """
Nas chamadas abaixo, troque, por exemplo: `create_issue(item, citation)` por `create_issue(item, citation.get("issue"))`.
Faça isso com todas.

2023-07-31 19:44 UTC, Rossi-Luciano commented on packtools/sps/formats/crossref.py
> +    """
@robertatakenaka a função que chama `create_issue` (e os demais creates) já está com um comentário similar a mais completo, veja:
```
Cria o elemento 'citation'.

        Parameters
        ----------
        item : dict
            Dicionário com dados de citação, como por exemplo:
            {
                "label": "1",
                "source": "Drug Alcohol Depend.",
                "main_author": {"surname": "Tran", "given_name": "B"},
                "all_authors": [
                    {"surname": "Tran", "given_name": "B"},
                    {"surname": "Falster", "given_name": "MO"},
                    {"surname": "Douglas", "given_name": "K"},
                    {"surname": "Blyth", "given_name": "F"},
                    {"surname": "Jorm", "given_name": "LR"},
                ],
                "volume": "150",
                "fpage": "85",
                "lpage": "91",
                "year": "2015",
                "issue": "4",
                "article_title": "Smoking and potentially preventable hospitalisation: the benefit of smoking cessation in
                                  older ages",
                "mixed_citation": "1. Tran B, Falster MO, Douglas K, Blyth F, Jorm LR. Smoking and potentially preventable
                                   hospitalisation: the benefit of smoking cessation in older ages. Drug Alcohol Depend.
                                   2015;150:85-91. DOI:\n            https://doi.org/10.1016/j.drugalcdep.2015.02.028",
            }

        Returns
        -------
        lxml.etree._Element
            <citation key="ref1">
                <journal_title>Drug Alcohol Depend.</journal_title>
                <author>Tran B</author>
                <volume>150</volume>
                <first_page>85</first_page>
                <cYear>2015</cYear>
                <article_title>Smoking and potentially preventable hospitalisation: the benefit of smoking cessation in older ages</article_title>
            </citation>
```

2023-07-31 19:57 UTC, robertatakenaka requested changes
Veja os comentários

2023-08-01 11:29 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
>      def _get_section_titles_and_paragraphs(self, attrib):
@Rossi-Luciano verificar conflito

2023-08-01 14:20 UTC, Rossi-Luciano commented on packtools/sps/formats/crossref.py
> +    """
@robertatakenaka nesse caso `citation` é um elemento xml que receberá a tag `issue` e seu respectivo valor que está no dicionário `item`.

2023-08-01 14:21 UTC, Rossi-Luciano commented on packtools/sps/formats/crossref.py
> +        """
@robertatakenaka aqui `citation` é um elemento xml, o dicionário é `item`.

2023-08-01 14:29 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
>      def _get_section_titles_and_paragraphs(self, attrib):
Ok @robertatakenaka

2023-08-08 09:53 UTC, robertatakenaka approved these changes

2023-08-08 09:54 UTC, merged