Reorganiza conteudo
scieloorg/packtools pull request #474
Opened 2023-10-09 14:59 UTC by Rossi-Luciano

#### O que esse PR faz?
Reorganiza o conteúdo do repositório em pastas específicas.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
NA.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #471 

### Referências
NA.

2023-10-09 15:21 UTC, robertatakenaka commented on lib/validator.py
> +import argparse
@Rossi-Luciano validator.py é um utilitário, logo deve ficar junto com os demais utilitários

2023-10-09 15:32 UTC, robertatakenaka commented on packtools/sps/utils/xml_utils.py
> +from lib import file_utils
@Rossi-Luciano suspeito que tenha que prefixar com `packtools.`: `from packtools.lib import file_utils`

2023-10-09 15:35 UTC, robertatakenaka commented on packtools/package_maker.py
> +from lib import file_utils
@Rossi-Luciano lib tem que ficar dentro do segundo `packtools`

2023-10-09 15:36 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar os comentários

2023-10-09 15:40 UTC, Rossi-Luciano commented on packtools/sps/utils/xml_utils.py
> +from lib import file_utils
OK @robertatakenaka

2023-10-09 15:40 UTC, Rossi-Luciano commented on packtools/package_maker.py
> +from lib import file_utils
OK @robertatakenaka

2023-10-10 20:39 UTC, robertatakenaka approved these changes

2023-10-10 20:40 UTC, merged