Validade general improvements
scieloorg/packtools pull request #487
Opened 2023-11-01 14:15 UTC by Rossi-Luciano

#### O que esse PR faz?
Corrige problemas remanescentes dos procedimentos de validação para: `xref`, afiliações e idiomas.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Avaliando os testes:
```
python3 -m unittest -v tests/sps/models/test_article_and_subarticles.py
python3 -m unittest -v tests/sps/validation/test_article_and_subarticles.py
python3 -m unittest -v tests/sps/validation/test_aff.py
python3 -m unittest -v tests/sps/validation/test_article_xref.py
```

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2023-11-01 14:17 UTC, robertatakenaka commented on packtools/sps/validation/article_xref.py
> +            'advice': 'For each xref[@rid="aff1"] must have least one corresponding element which @id="aff1"'
faltou `at` (at least)

2023-11-01 14:21 UTC, robertatakenaka commented on tests/sps/models/test_article_and_subarticles.py
> +            expected = ['en', 'pt', 'es']
@Rossi-Luciano o que fica "dentro" de with é somente a instrução relacionada com o arquivo.
Observe que colocando instruções dentro do `with` o arquivo somente ficará fechado após concluir todas as instruções dentro de `with`. É desnecessário manter o arquivo aberto enquanto executa as demais instruções

2023-11-01 14:22 UTC, robertatakenaka requested changes
corrigir os dois pontos comentados

2023-11-02 19:09 UTC, Rossi-Luciano commented on packtools/sps/validation/article_xref.py
> +            'advice': 'For each xref[@rid="aff1"] must have least one corresponding element which @id="aff1"'
OK @robertatakenaka

2023-11-02 19:09 UTC, Rossi-Luciano commented on tests/sps/models/test_article_and_subarticles.py
> +            expected = ['en', 'pt', 'es']
OK @robertatakenaka

2023-11-06 11:41 UTC, robertatakenaka approved these changes

2023-11-06 11:41 UTC, merged