Article type vs subject
scieloorg/packtools pull request #500
Opened 2023-11-16 01:44 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona validação para `article-type` e `subject.`

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Avaliando os testes.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2023-11-17 10:15 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +        if not article_type_list:
aqui seria subject list, no entanto, lembre-se de que falei que nem todos os periódicos adotam título de seção?

2023-11-17 10:18 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +                indice, subject = most_similar(similarity([article_subject], article_type))
Quando disse para fazer os dois tipos de validações, não devem ser com if e else, simplesmente faça outro método. Pois o sistema cliente, adota a validação que acreditar que é mais adequada ou ambas. Lembre-se de que como é uma biblioteca, você fornece as opções mais genéricas.

2023-11-17 10:19 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +                        'got_value': f'{indice * 100:,.2f}%',
o retorno deve ser numérico

2023-11-17 10:20 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
>                          'validation_type': 'match',
acredito que a validation_type seja 'similarity'

2023-11-17 10:22 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +                        'expected_value': 'The highest possible match rate',
acho que pode ser None, pois não se aplica. Não cabe à biblioteca packtools julgar, o usuario da biblioteca deve fazer o julgamento. Talvez, o mais próximo de uma boa solução é o usuário já informar a porcentagem mínima esperada, aí neste caso o valor esperado pode ser o valor da porcentagem fornecida.

2023-11-17 10:23 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +                        'advice': 'Change the {} to one item of this list: {}'.format(article_subject, " | ".
comentei que subject já está fornecido, logo o produtor de xml não pode alterar subject.

2023-11-17 10:25 UTC, robertatakenaka commented on tests/sps/validation/test_article_and_subarticles.py
> +                'expected_value': ['original article', 'artigo original', 'artículo original'],
contrário, a partir do subject, concluímos se o article-type está correto ou não

2023-11-17 10:33 UTC, robertatakenaka requested changes
Considerar:
- dados que são de responsabilidade do editor não podem ser considerados errados, mas sim aquilo que os produtores inseriram como dado. Sendo assim, o que está sendo validado é o article-type e não o subject.
- packtools não deve julgar, exceto se previamente é fornecido a ele os parâmetros de julgamento. Acho que seria sim interessante prover qual seria a porcentagem de similaridade. Inclusive isso pode ser um tipo de validação novo.
- subject não é obrigatório, no entanto, uma vez que o periódico não tem este dado, a validação tem que ser de expor que o dado existe, mas não deveria. Da parte do packtools, o resultado deve ser informar que a lista está vazia, pode até levantar sim exceção, mas não com a mensagem de que é obrigatório, a mensagem pode ser "lista de subjects ausente" e ok levantar exceção que deve ser tratada no cliente da biblioteca, desde que esteja documentado.

2023-11-20 15:49 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +        if not article_type_list:
OK @robertatakenaka

2023-11-20 15:49 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +                indice, subject = most_similar(similarity([article_subject], article_type))
OK @robertatakenaka

2023-11-20 15:49 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +                        'got_value': f'{indice * 100:,.2f}%',
OK @robertatakenaka

2023-11-20 15:49 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
>                          'validation_type': 'match',
OK @robertatakenaka

2023-11-20 15:49 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +                        'expected_value': 'The highest possible match rate',
OK @robertatakenaka

2023-11-20 15:49 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +                        'advice': 'Change the {} to one item of this list: {}'.format(article_subject, " | ".
OK @robertatakenaka

2023-11-20 15:49 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_and_subarticles.py
> +                'expected_value': ['original article', 'artigo original', 'artículo original'],
OK @robertatakenaka

2023-11-22 12:22 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +            list: language_codes_list
@Rossi-Luciano é o contrário:

```python
nome da variavel : tipo da variavel
     descricao
```
Consulte: https://pandas.pydata.org/docs/development/contributing_docstring.html

2023-11-22 12:25 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +            xml: ElementTree
Remover `xml: ElementTree`

Consulte:
https://pandas.pydata.org/docs/development/contributing_docstring.html

```python
class Series:
    def plot(self, kind, color='blue', **kwargs):
        """
        Generate a plot.

        Render the data in the Series as a matplotlib plot of the
        specified kind.

        Parameters
        ----------
        kind : str
            Kind of matplotlib plot.
        color : str, default 'blue'
            Color name or rgb code.
        **kwargs
            These parameters will be passed to the matplotlib plotting
            function.
        """
        pass
```

2023-11-22 12:28 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +            'xpath': './article/article-type .//subject',
`./article/@article-type`

Coloque `@` nos nomes de atributos

2023-11-22 12:32 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +                    'advice': f'If the similarity rate is lower than the expected rate, consider changing the {article_type}'
Melhor sugerir:
```verify the value of  ./article/@article-type```
no lugar de
```consider changing the```

2023-11-22 12:35 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +    def validate_doi(self):
@Rossi-Luciano para melhor recuperação de PR (consulta no futuro), o DOI deveria ficar em um PR particular

2023-11-22 12:37 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +            'expected_value': 'DOI identifier',
Trocar `'expected_value': 'DOI identifier',`, por `'expected_value': 'article DOI',` (ou sub-article idioma DOI) para saber DOI qual é

2023-11-22 12:50 UTC, robertatakenaka commented on packtools/sps/models/article_and_subarticles.py
> +            return subject.text
return self.xmltree.find**text**('.//subject')

2023-11-22 12:55 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +        self.doi = DoiWithLang(self.xmltree).main_doi
@Rossi-Luciano a ideia original é que tenhamos várias classes com propósitos específicos. Então, a validação de DOI deveria ter sua própria classe. 
Na verdade até article_type poderia ter a sua, subject também poderia ter a sua própria.

ArticleValidation deveria deixar de existir, caso contrário, tudo é ArticleValidation.

A ideia era que as classes ficaria pequenas.
Observe a crescente quantidade de parâmetros que estão sendo adicionados.

2023-11-22 12:56 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +        Params
colocar descrição em todos os comentários. Exemplo:

Verifica a presença ou ausência do atributo `@article-type` dos elementos article e sub-article. Pode colocar exemplo de XML

2023-11-22 13:02 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +    def validate_article_type_vs_subject_similarity(self, expected_similarity=0):
@Rossi-Luciano Modifica o elemento de comparação. No lugar de comparar article-type com subject, você vai comparar a similaridade de subject do XML com uma lista de Subjects fornecida. Um detalhe relevante é que a lista fornecida deve conter o idioma em que estão os subjects. Então vc vai comparar o subject do xml + idioma no xml como item da lista + seu idioma correspondente. 
O article-type está sempre em inglês, o Subject pode estar em outro idioma, logo a taxa de similaridade pode dar bem baixa.

2023-11-22 13:05 UTC, robertatakenaka commented on packtools/sps/validation/similarity_utils.py
> +SUBJECTS_VS_ARTICLE_TYPE = dict([
@Rossi-Luciano pode consultar os links, mas não se apegue à solução anteriormente dada. Estamos realizando uma nova abordagem.

2023-11-22 18:03 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +            list: language_codes_list
OK @robertatakenaka .

2023-11-22 18:03 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +            xml: ElementTree
OK @robertatakenaka .

2023-11-22 18:03 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +            'xpath': './article/article-type .//subject',
OK @robertatakenaka .

2023-11-22 18:03 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +                    'advice': f'If the similarity rate is lower than the expected rate, consider changing the {article_type}'
OK @robertatakenaka .

2023-11-22 18:03 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +    def validate_doi(self):
OK @robertatakenaka .

2023-11-22 18:04 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +            'expected_value': 'DOI identifier',
OK @robertatakenaka .

2023-11-22 18:04 UTC, Rossi-Luciano commented on packtools/sps/models/article_and_subarticles.py
> +            return subject.text
OK @robertatakenaka .

2023-11-22 18:04 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +        self.doi = DoiWithLang(self.xmltree).main_doi
OK @robertatakenaka .

2023-11-22 18:04 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +        Params
OK @robertatakenaka .

2023-11-22 18:04 UTC, Rossi-Luciano commented on packtools/sps/validation/article_and_subarticles.py
> +    def validate_article_type_vs_subject_similarity(self, expected_similarity=0):
OK @robertatakenaka .

2023-11-22 18:04 UTC, Rossi-Luciano commented on packtools/sps/validation/similarity_utils.py
> +SUBJECTS_VS_ARTICLE_TYPE = dict([
OK @robertatakenaka .

2023-11-23 17:22 UTC, robertatakenaka commented on packtools/sps/validation/article_and_subarticles.py
> +class ArticleDoiValidation:
@Rossi-Luciano fazer a validação de presença de DOI para os sub-articles (translation)

2023-11-23 17:23 UTC, robertatakenaka approved these changes

2023-11-23 17:23 UTC, merged