Doi validation
scieloorg/packtools pull request #501
Opened 2023-11-27 16:31 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona classes de validação para DOI.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_article_doi.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2023-11-27 18:25 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +        translations_lang_with_doi = [item['lang'] for item in self.dois if item['lang'] in translations_lang]
@Rossi-Luciano a idéia é de existência é a mesma adotada para o main. Para cada sub-article (translation), use o idioma para identificar cada sub-article + seu `@id`, e indique o DOI encontrado, existente.

2023-11-27 18:26 UTC, robertatakenaka requested changes
A validação de DOI das traduções foi mal entendida. Refazer.

2023-11-28 13:30 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +        translations_lang_with_doi = [item['lang'] for item in self.dois if item['lang'] in translations_lang]
OK @robertatakenaka

2023-11-28 13:30 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                'advice': 'XML research-article does not present a DOI'
OK @robertatakenaka

2023-11-28 13:30 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +            'advice': None if validated else 'The translation sub-article for {} languages does not present a DOI'.format(diff)
OK @robertatakenaka

2023-11-28 13:31 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +            'advice': None if validated else 'The following DOIs are not unique: {}'.format(" | ".join(diff))
OK @robertatakenaka

2023-11-28 13:31 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_doi.py
> +            'message': 'Got 10.1590/1518-8345.2927.3231 expected a DOI',
OK @robertatakenaka

2023-11-28 15:35 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                'message': 'Got 10.1590/2176-4573e59270 expected sub-article DOI',
@Rossi-Luciano corrigir é o mesmo caso do main doi

2023-11-28 15:36 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                        'advice': None if doi else 'Provide a valid DOI for the sub-article translation ({}) whose '
which (no lugar de whose)

2023-11-28 15:38 UTC, robertatakenaka requested changes
@Rossi-Luciano Realizar os ajustes solicitados

2023-11-29 13:13 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                'message': 'Got 10.1590/2176-4573e59270 expected sub-article DOI',
OK @robertatakenaka

2023-11-29 13:13 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                        'advice': None if doi else 'Provide a valid DOI for the sub-article translation ({}) whose '
OK, @robertatakenaka

2023-11-29 13:31 UTC, robertatakenaka approved these changes

2023-11-29 13:31 UTC, merged