Date validation
scieloorg/packtools pull request #504
Opened 2023-11-29 17:28 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona funções de validação para data de publicação de artigo.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_dates.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2023-11-29 21:51 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                    'xpath': './/front//pub-date/@date-type:pub',
@Rossi-Luciano 
`.//front//pub-date[@date-type='pub']`

2023-11-29 21:51 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                    'validation_type': 'format (number of digits)',
conteúdo de validation_type deve ser somente 'format'

2023-11-29 21:54 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +        except ValueError as e:
@Rossi-Luciano experimenta passar letras no lugar de month, talvez ocorra outra exceção, se sim adiciona na linha 157. Aí será necessário colocar as exceção entre parêntesis e separar com vírgula, por ex.: 
```python
except (ValueError, TypeError) as e:
```

2023-11-29 21:55 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            future_date = pub_date.year - current_date.year > 0
@Rossi-Luciano melhor calcular em dias pois nas viradas de ano isso não vai funcionar bem

2023-11-29 21:56 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            advise = None if not future_date else 'The publication date is in the future, consider replacing it with a date in the past'
use a grafia `advice` para a variável

2023-11-29 21:58 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            future_date = pub_date.year - current_date.year > 0
Sugiro adicionar como parâmetro a tolerância em dias de diferença da data de publicação. Ou seja, a aplicação cliente pode fornecer o quanto de diferença seria tolerável que a data no futuro seja aceitável.

2023-11-29 22:04 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'title': 'Article pub-date validation',
No lugar de: `'Article pub-date validation'`, usar `'Article pub-date day validation'`

2023-11-29 22:04 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'xpath': './/front//pub-date/@date-type:pub',
`.//front//pub-date[@date-type="pub"]/day`

2023-11-29 22:05 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'validation_type': 'format (number of digits)',
usar só `format`

2023-11-29 22:05 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'expected_value': 'day represented with 2 digits',
Usar: `'03'`

2023-11-29 22:06 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'message': 'Got 2 expected 2 numeric digits',
Got 03, expected 03

2023-11-29 22:06 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'message': 'Got 4 expected 4 numeric digits',
mesmo vale para mês e ano

2023-11-29 22:08 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'validation_type': 'format (valid date)',
A validação está relacionada a valor e não ao formato

2023-11-29 22:10 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'expected_value': 'A date in the format: YYYY-MM-DD',
data inferior a given_date

2023-11-29 22:13 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +            }
OK

2023-11-29 22:15 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'message': 'Got 2 expected 2 numeric digits',
Caso o usuario, coloque 3, você diz que está incorreto: `Got 3, expected 03`

2023-11-29 22:19 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                of this list: pt | en | es'
atualizar comentário

2023-11-29 22:20 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            future_date = pub_date.year - current_date.year > 0
Para comparar pode usar: `data_encontrada <= data_futura`

2023-11-29 22:27 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'expected_value': 'day represented with 2 digits',
Quando não for possível indicar a formatação correta, pode colocar `'day represented with 2 digits'`

2023-11-30 14:58 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +                    'xpath': './/front//pub-date/@date-type:pub',
OK @robertatakenaka

2023-11-30 14:58 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +                    'validation_type': 'format (number of digits)',
OK @robertatakenaka

2023-11-30 14:58 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            advise = None if not future_date else 'The publication date is in the future, consider replacing it with a date in the past'
OK @robertatakenaka

2023-11-30 15:19 UTC, Rossi-Luciano commented on tests/sps/validation/test_dates.py
> +                'xpath': './/front//pub-date/@date-type:pub',
OK @robertatakenaka

2023-11-30 15:19 UTC, Rossi-Luciano commented on tests/sps/validation/test_dates.py
> +                'validation_type': 'format (number of digits)',
OK @robertatakenaka

2023-11-30 15:23 UTC, Rossi-Luciano commented on tests/sps/validation/test_dates.py
> +                'validation_type': 'format (valid date)',
OK @robertatakenaka

2023-11-30 17:10 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +    def validate_article_date(self, future_year, future_month, future_day):
@Rossi-Luciano da data futura deve ter o formato YYYY-MM-DD

2023-11-30 17:14 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            validated = pub_date < future_date
Pode-ser comparar   strings: 'YYYY-MM-DD' <= 'YYYY-MM-DD'

2023-11-30 17:15 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            'xpath': './/front//pub-date[@date-type:pub]',
`[@date-type="pub"]`

2023-11-30 17:17 UTC, robertatakenaka requested changes
Realizar correções

2023-12-01 12:41 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +                of this list: pt | en | es'
OK @robertatakenaka

2023-12-01 12:41 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +    def validate_article_date(self, future_year, future_month, future_day):
OK @robertatakenaka

2023-12-01 12:41 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            validated = pub_date < future_date
OK @robertatakenaka

2023-12-01 12:41 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            advice = None if validated else 'The publication date is in the future, consider replacing it with a date in the past'
OK @robertatakenaka

2023-12-01 12:42 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            'xpath': './/front//pub-date[@date-type:pub]',
OK @robertatakenaka

2023-12-01 12:55 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +                'xpath': './/front//pub-date[@date-type:"pub"]',
`@date-type:"pub"` por `@date-type="pub"` (Trocar `:` por `=`)

2023-12-01 12:57 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            _ = date_dict_to_date(self.article_date)
qual é a função do `_` neste caso?

2023-12-01 13:01 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            advice = None if validated else 'The publication date is in the future, consider replacing it with a date in the past'
mude de `'The publication date is in the future, consider replacing it with a date in the past'` para
`'The publication date must be a date before or equal to {}'.format(future_date)`

2023-12-01 13:28 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            advice = None if validated else 'The publication date is in the future, consider replacing it with a date in the past'
OK @robertatakenaka

2023-12-01 13:28 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +                'xpath': './/front//pub-date[@date-type:"pub"]',
OK @robertatakenaka

2023-12-01 13:29 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            'expected_value': 'A date in the format: YYYY-MM-DD less than {}'.format(future_date),
OK @robertatakenaka

2023-12-01 13:46 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            _ = date_dict_to_date(self.article_date)
não está sendo usada em nenhum local

2023-12-03 23:45 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            _ = date_dict_to_date(self.article_date)
@robertatakenaka, `date_dict_to_date(self.article_date)` é só pra verificar se os parâmetros podem ser convertidos em uma data.

2023-12-04 11:47 UTC, robertatakenaka commented on packtools/sps/validation/dates.py
> +            pub_date = date_dict_to_date(self.article_date)
@Rossi-Luciano a variável parece que não está sendo usada. Remover.

2023-12-05 11:55 UTC, Rossi-Luciano commented on packtools/sps/validation/dates.py
> +            pub_date = date_dict_to_date(self.article_date)
OK @robertatakenaka

2023-12-06 12:09 UTC, Rossi-Luciano commented on tests/sps/validation/test_dates.py
> +                'advice': 'Fix the following issue on the given date: year 0 is out of range'
OK @robertatakenaka

2023-12-07 18:40 UTC, robertatakenaka commented on tests/sps/validation/test_dates.py
> +                'message': 'Got 202 expected 0202',
hum... isso me faz pensar que temos que adotar uma data mínima. Vamos aprovar este PR e considerar um complemento deste issue também receber uma data mínima fornecida pela aplicação cliente.

2023-12-07 18:42 UTC, robertatakenaka approved these changes
Veja o comentário sobre data mínima. Deixe para fazer como novo issue.

2023-12-07 18:42 UTC, merged