Doi registered
scieloorg/packtools pull request #521
Opened 2024-01-03 19:02 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona procedimento de validação para a verificação se o DOI é registrado. Além disso, padroniza o retorno de outras funções de validação, envolvendo DOI, para retornarem uma lista de dicionários ao invés de um único dicionário. Essa última atualização tem por objetivo padronizar os retornos das funções de validação.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_article_doi.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-01-04 18:31 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                'expected_value': self.doi if self.doi else 'article DOI',
Melhoria:
```python
'expected_value': self.doi or 'article DOI',
```

2024-01-04 18:33 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'message': 'Got {} expected {}'.format(doi, doi if doi else 'sub-article DOI'),
@Rossi-Luciano **sempre** que houver sub-article, indicar juntamente o `@article-type` e `@xml:lang`

2024-01-04 18:34 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'expected_value': doi if doi else 'sub-article DOI',
@Rossi-Luciano **sempre** que houver sub-article, indicar juntamente o `@article-type` e `@xml:lang`

2024-01-04 18:34 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'expected_value': doi if doi else 'sub-article DOI',
Neste caso em particular, pode omitir o `@article=type` já que o contexto é translation

2024-01-04 18:36 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'got_value': 'DOIs identified: 10.1590/2176-4573p59270 | 10.1590/2176-4573e59270',
manter só os valores sem `'DOIs identified: `

2024-01-04 18:38 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'got_value': 'DOIs identified: 10.1590/2176-4573p59270 | 10.1590/2176-4573e59270',
Deixar sempre expected_value e got_value o mais puros possíveis em formato de dado.
`got_value` poderia conter um dicionário no formato `{"en": "numero do doi", "pt": "..."}` ou uma lista de dicionários": `[{"language": "en", "doi": "xxxx"}, ...]`
Assim, a aplicação cliente pode usar os dados.
Mesmo porque no formato texto há o **message**

2024-01-04 18:45 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'got_value': 'DOIs identified: 10.1590/2176-4573p59270 | 10.1590/2176-4573e59270',
enfim, evitar got e expected em formato de mensagem, e eles tem que ser coerentes

2024-01-04 18:53 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +        is_valid = callable_get_validate(self.doi)
@Rossi-Luciano o Callable deve retornar uma estrutura JSON definida por você, de onde você deve conseguir comparar author e título (do idioma do doi correspondente, ou na falta dele, no título principal). Por exemplo:

```json
{"doi-list": [{"title": "", "language": "", "doi": ""}, {"title": "", "language": "", "doi": ""}, ], "authors": []}
```

Aí recebendo isso, você compara com os dados correspondentes do XML.

2024-01-06 02:44 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                'expected_value': self.doi if self.doi else 'article DOI',
OK @robertatakenaka.

2024-01-06 02:44 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                    'message': 'Got {} expected {}'.format(doi, doi if doi else 'sub-article DOI'),
OK @robertatakenaka.

2024-01-06 02:45 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                    'expected_value': doi if doi else 'sub-article DOI',
OK @robertatakenaka.

2024-01-06 02:45 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                    'got_value': 'DOIs identified: 10.1590/2176-4573p59270 | 10.1590/2176-4573e59270',
OK @robertatakenaka.

2024-01-06 02:45 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +        is_valid = callable_get_validate(self.doi)
OK @robertatakenaka, alterei um pouco o formato do dicionário.

2024-01-08 11:42 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +    return 'Validate not found'
Use `raise NotImplementedError`

2024-01-08 11:46 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    'message': 'Got {} expected {}'.format(doi, doi if doi else 'sub-article DOI'),
@Rossi-Luciano faltou aqui arrumar o expected e message: no lugar de `sub-article DOI` adicionar `f"sub-article ({lang}) DOI"`

2024-01-08 11:50 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +            is_valid = obtained_doi == expected_doi and obtained_title == expected_title and obtained_authors == expected_authors
@Rossi-Luciano valide cada ítem separado, porque desta forma o usuário saberá onde exatamente está o problema

2024-01-08 11:54 UTC, robertatakenaka requested changes
Considerar sempre uma validação mais atômica

2024-01-09 03:12 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +    return 'Validate not found'
OK, @robertatakenaka

2024-01-09 03:12 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +            is_valid = obtained_doi == expected_doi and obtained_title == expected_title and obtained_authors == expected_authors
OK, @robertatakenaka

2024-01-09 13:03 UTC, robertatakenaka reviewed
@Rossi-Luciano acrescente os seguintes testes:
a) o resultado da função call_... retorna que o DOI não está registrado (você projeta como a aplicação cliente deve informar isso para o packtools); como resposta da validação, você retorna que o DOI não está registrado
b) o resultado da função retorna dados de outro artigo, inclusive a quantidade de autores diverge
c) teste caso de título ausente no XML comparando com título retornado da função
d) teste caso de autores ausentes no XML comparando com autores retornado da função
e) teste caso de título ausente no resultado da função comparando com título do XML
f) teste caso de autores ausentes resultado da função comparando com autores do XML

2024-01-10 00:12 UTC, Rossi-Luciano commented
OK, @robertatakenaka

2024-01-11 13:31 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                    validations.append(('author', False, author, None))
@Rossi-Luciano não alterar a ordem

2024-01-11 16:06 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                    validations.append(('author', False, author, None))
OK, @robertatakenaka

2024-01-14 20:44 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                # Resposta para o caso de não haver identificação do DOI
@Rossi-Luciano colocar como advice: `consulte novamente após DOI ter sido registrado`.

No XML, não é obrigatório o DOI estar registrado. Mesmo porque como o XML é entrada no fluxo, o valor do DOI encontrado no XML é usado para fazer seu cadastro no CrossRef.

2024-01-14 23:46 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                # Resposta para o caso de não haver identificação do DOI
OK, @robertatakenaka

2024-01-16 10:26 UTC, robertatakenaka approved these changes

2024-01-16 10:26 UTC, merged