Refactor: adaptar a classe de validação de ISSN's ao padrão adotado
scieloorg/packtools pull request #523
Opened 2024-01-04 15:28 UTC by Rossi-Luciano

#### O que esse PR faz?
Refatora o procedimento de validação para ISSN's de modo a atender ao padrão adotado para validações.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_journal_meta.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-01-04 16:52 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +                    'message': 'Got <issn pub-type="ppub">0034-8910</issn> expected one item of this list: ppub: 0034-8910 | epub: 1518-8787',
@Rossi-Luciano está muito misturado. O exemplo deve ser coerente. Pelo XML e pelo esperado, a resposta é OK, logo o expected_value e got teriam que ser **iguais**. O valor escrito em `message` não está coerente nem com o obtido nem com o esperado

2024-01-04 16:54 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +                'xpath': './/journal-meta//issn[@pub-type=*]',
@Rossi-Luciano no lugar `*` use explicitamente qual é o tipo do issn (`f'.//journal-meta//issn[@pub-type=\'{issn_type}\']'`)

2024-01-04 16:54 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +                'validation_type': 'value in list',
'value'

2024-01-04 16:55 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +                'expected_value': issns_dict,
@Rossi-Luciano no lugar issns_dict, coloque o valor esperado do issn de acordo com o tipo

2024-01-04 16:56 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +                    " | ".join([f"{t}: {v}" for t, v in issns_dict.items()])
@Rossi-Luciano dado do issn correspondente ao tipo mencionado na linha 60 `'xpath': './/journal-meta//issn[@pub-type=*]',`

2024-01-04 16:57 UTC, robertatakenaka commented on packtools/sps/validation/journal_meta.py
> +                    " | ".join([f"{t}: {v}" for t, v in issns_dict.items()]))
dado do issn correspondente ao tipo mencionado na linha 60 'xpath': './/journal-meta//issn[@pub-type=*]',

2024-01-04 16:58 UTC, robertatakenaka requested changes
Corrigir resposta

2024-01-08 01:11 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +                    'message': 'Got <issn pub-type="ppub">0034-8910</issn> expected one item of this list: ppub: 0034-8910 | epub: 1518-8787',
OK, @robertatakenaka

2024-01-08 01:11 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +                'xpath': './/journal-meta//issn[@pub-type=*]',
OK, @robertatakenaka

2024-01-08 01:11 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +                'validation_type': 'value in list',
OK, @robertatakenaka

2024-01-08 01:12 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +                'expected_value': issns_dict,
OK, @robertatakenaka

2024-01-08 01:12 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +                    " | ".join([f"{t}: {v}" for t, v in issns_dict.items()])
OK, @robertatakenaka

2024-01-08 01:12 UTC, Rossi-Luciano commented on packtools/sps/validation/journal_meta.py
> +                    " | ".join([f"{t}: {v}" for t, v in issns_dict.items()]))
OK, @robertatakenaka

2024-01-08 12:23 UTC, robertatakenaka approved these changes

2024-01-08 12:24 UTC, merged