Feat: adiciona valiadações para ORCID
scieloorg/packtools pull request #525
Opened 2024-01-08 15:50 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona validações para verificação se o elemento ORCID é único e possui registro válido.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_article_authors.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-01-09 13:19 UTC, robertatakenaka reviewed
@Rossi-Luciano adicione testes que cujo resultado é 
```python
{
        '0990-0001-0058-4853': None,
        '0000-3333-1238-6873': None,
    }

2024-01-10 13:58 UTC, Rossi-Luciano commented
OK, @robertatakenaka

2024-01-11 11:24 UTC, robertatakenaka commented on tests/sps/validation/test_article_authors.py
> +                'got_value': ['0990-0001-0058-4853', None],
@Rossi-Luciano Os valores OBTIDOS são aqueles encontrados no XML. O retorno de `callable_*` é o valor esperado. No entanto, como é `None`, não podemos afirmar que o esperado é _None_. Neste caso, tem que ser informado que o ORCID não se encontra registrado ou não é possível fazer a validação no momento. Podemos adicionar mais um retorno no `callable_*` para indicar se o request foi concluído ou se houve alguma falha, assim distinguimos o que é ORCID não registrado de falha de conexão.

2024-01-11 11:25 UTC, robertatakenaka requested changes
Revisar os valores OBTIDO x ESPERADO

2024-01-13 22:01 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_authors.py
> +                'advice': "The author None has 0990-0001-0058-4853 as ORCID and its register is "
OK, @robertatakenaka

2024-01-14 20:50 UTC, robertatakenaka commented on packtools/sps/validation/article_authors.py
> +                'advice': None if is_valid else "ORCID {} is not registered for the obtained author or did not"
Acho que a mensagem é `ORCID {} não está registrado para nenhum autor`

2024-01-14 23:46 UTC, Rossi-Luciano commented on packtools/sps/validation/article_authors.py
> +                'advice': None if is_valid else "ORCID {} is not registered for the obtained author or did not"
OK, @robertatakenaka

2024-01-16 10:28 UTC, robertatakenaka approved these changes

2024-01-16 10:29 UTC, merged