Robertatakenaka refatora keywords
scieloorg/packtools pull request #576
Opened 2024-03-18 17:05 UTC by Rossi-Luciano

#### O que esse PR faz?
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.

#### Onde a revisão poderia começar?
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.

#### Como este poderia ser testado manualmente?
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.

#### Algum cenário de contexto que queira dar?
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.

### Screenshots
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.

#### Quais são tickets relevantes?
Indique uma issue ao qual o pull request faz relacionamento.

### Referências
Indique as referências utilizadas para a elaboração do pull request.

2024-03-19 20:33 UTC, robertatakenaka commented on packtools/sps/models/kwd_group.py
> +                d[item['lang']] = []
```python
d.setdefault(item['lang'], [])
```

2024-03-19 20:34 UTC, robertatakenaka commented on tests/sps/models/test_kwd_group.py
> +        for i, item in enumerate(obtained):
@Rossi-Luciano sempre percorre pelo expected

2024-03-19 20:34 UTC, robertatakenaka commented on tests/sps/models/test_kwd_group.py
> +        for i, item in enumerate(obtained):
@Rossi-Luciano sempre percorre pelo expected

2024-03-19 20:35 UTC, robertatakenaka requested changes
Verificar comentários

2024-03-20 12:20 UTC, Rossi-Luciano commented on packtools/sps/models/kwd_group.py
> +                d[item['lang']] = []
OK @robertatakenaka

2024-03-20 12:20 UTC, Rossi-Luciano commented on tests/sps/models/test_kwd_group.py
> +        for i, item in enumerate(obtained):
OK, @robertatakenaka

2024-03-20 12:20 UTC, Rossi-Luciano commented on tests/sps/models/test_kwd_group.py
> +        for i, item in enumerate(obtained):
OK, @robertatakenaka

2024-03-20 17:21 UTC, robertatakenaka commented on packtools/sps/models/kwd_group.py
> +                d.setdefault(item['lang'], [])
@Rossi-Luciano remover a linha 362

2024-03-21 13:09 UTC, merged