Feat: highlights and visual abstracts
scieloorg/packtools pull request #605
Opened 2024-05-01 19:31 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona modelos para dados de `highlights` e `visual abstracts`.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/models/test_article_abstract.py`

#### Algum cenário de contexto que queira dar?
Posteriormente, deve ser criada a classe de validação para esses elementos. Não identifiquei o que será validado.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-05-07 14:49 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +        for node in self.xmltree.xpath(".//abstract"):
`self.xmltree.xpath(".//abstract[@abstract-type='key-points']")`

2024-05-07 14:49 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +            if node.get("abstract-type") == "key-points":
Remover esta linha

2024-05-07 14:59 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +        for abstract in self.xmltree.xpath(".//abstract"):
Usar `self.xmltree.xpath(".//abstract[@abstract-type='graphical']")`

2024-05-10 11:24 UTC, robertatakenaka requested changes
@Rossi-Luciano Realizar correções

2024-05-16 11:24 UTC, robertatakenaka approved these changes

2024-05-16 11:26 UTC, robertatakenaka requested changes
@Rossi-Luciano Notei que não estão contextualizados em article e sub-article. Alterar considerando isso. Lembre-se que é necessário identificar se é de article ou sub-article, id, lang, article-type

2024-05-16 15:02 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +        for node in self.xmltree.xpath(".//abstract"):
OK, @robertatakenaka

2024-05-16 15:02 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +            if node.get("abstract-type") == "key-points":
OK, @robertatakenaka

2024-05-16 15:02 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +        for abstract in self.xmltree.xpath(".//abstract"):
OK, @robertatakenaka

2024-05-16 15:03 UTC, Rossi-Luciano commented
@robertatakenaka as classes de validação foram inseridas

2024-05-20 11:50 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +            tags_to_convert_to_html=None,
@Rossi-Luciano indentação estava correta. Use o black para formatar o código automaticamente. No entanto, sugiro que você use em um commit separado para não misturar mudanças de código com mudanças de formatação.

2024-05-20 11:53 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +def _get_parent_context(xmltree):
@Rossi-Luciano sugiro usar a solução de criar a classe ArticleHighlights, Highlights (contextualizado no article / sub-article), Highlight. Esta solução deve ser padrão para todos os elementos.

2024-05-20 11:54 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +def _get_parent_context(xmltree):
O mesmo para VisualAbstract

2024-05-22 11:54 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +            tags_to_convert_to_html=None,
OK, @robertatakenaka

2024-05-22 11:54 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +def _get_parent_context(xmltree):
OK, @robertatakenaka

2024-05-23 11:59 UTC, robertatakenaka commented on packtools/sps/validation/article_abstract.py
> +                resp["response"] = response_type_for_absent
@Rossi-Luciano só pode haver esta atribuição se is_valid é False

2024-05-27 11:41 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +        for abstract in self.node.xpath(".//abstract[@abstract-type='key-points']"):
@Rossi-Luciano considerar o trans-abstract

2024-05-31 15:25 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +        for abstract in self.node.xpath(".//abstract[@abstract-type='key-points']"):
OK, @robertatakenaka

2024-06-13 11:33 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +    def highlights(self):
@Rossi-Luciano use p no lugar de highlights

2024-06-13 11:33 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +            "highlights": list(self.highlights)
@Rossi-Luciano use p no lugar de highlights

2024-06-13 11:35 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +                yield highlight.text
@Rossi-Luciano este text teria que tratar com  função que lida com as tags de estilo

2024-06-13 11:39 UTC, robertatakenaka commented on packtools/sps/validation/article_abstract.py
> +                data=None
@Rossi-Luciano adiciona error_level

2024-06-13 11:39 UTC, robertatakenaka commented on packtools/sps/validation/article_abstract.py
> +                resp["response"] = response_type_for_absent
@Rossi-Luciano isso é o mesmo que error_level?

2024-06-13 11:40 UTC, robertatakenaka commented on packtools/sps/validation/article_abstract.py
> +                    obtained=highlight.get("highlights"),
@Rossi-Luciano os dois iguais?

2024-06-13 11:45 UTC, robertatakenaka commented on packtools/sps/validation/article_abstract.py
> +                    parent_id=highlight.get("parent_id"),
@Rossi-Luciano está faltando parent_article_type e parent_languague

2024-06-13 11:53 UTC, robertatakenaka requested changes
@Rossi-Luciano Verificar a questão do node.text e adicionar parent_article_type e parent_lang

2024-06-17 14:16 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +    def highlights(self):
OK, @robertatakenaka

2024-06-17 14:17 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +            "highlights": list(self.highlights)
OK, @robertatakenaka

2024-06-17 14:17 UTC, Rossi-Luciano commented on packtools/sps/models/article_abstract.py
> +                yield highlight.text
OK, @robertatakenaka

2024-06-17 14:17 UTC, Rossi-Luciano commented on packtools/sps/validation/article_abstract.py
> +                data=None
OK, @robertatakenaka

2024-06-17 14:17 UTC, Rossi-Luciano commented on packtools/sps/validation/article_abstract.py
> +                resp["response"] = response_type_for_absent
Sim @robertatakenaka, foi corrigido

2024-06-17 14:17 UTC, Rossi-Luciano commented on packtools/sps/validation/article_abstract.py
> +                    parent_id=highlight.get("parent_id"),
OK, @robertatakenaka

2024-07-17 11:18 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +            return graphic_node.get('{http://www.w3.org/1999/xlink}href')
@Rossi-Luciano considerar que pode haver mais de um graphic pois ao passar pelo otimizador, a miniatura e a imagem jpg ou png são criadas, e se cria também o elemento alternatives

2024-07-17 11:19 UTC, robertatakenaka commented on packtools/sps/validation/article_abstract.py
> +    def highlight_validation(self, error_level=None):
@Rossi-Luciano adicionar docstring em particular para indicar o valor default de error_level em todas as validações

2024-07-17 11:21 UTC, robertatakenaka requested changes
considerar alternatives em visual abstracts

2024-07-17 11:23 UTC, robertatakenaka commented on packtools/sps/models/article_abstract.py
> +            return graphic_node.get('{http://www.w3.org/1999/xlink}href')
@Rossi-Luciano Preciso esclarecer que pode haver casos de XML apenas com 1 graphic, sem alternatives, mas também caso de alternatives, com vários graphic. O modelo tem que funcionar nos dois casos.

2024-07-17 11:40 UTC, merged