Refactor: adiciona contexto às respostas das validações e lista controlada de códigos de países
scieloorg/packtools pull request #625
Opened 2024-06-03 15:32 UTC by Rossi-Luciano

#### O que esse PR faz?

1. Adiciona contexto ao modelo `Affiliation` e os testes correspondentes;
2. Adiciona valores às respostas da validação;
3. Adiciona lista controlada (JSON) para `country_codes_list`

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_aff.py `
`python3 -m unittest -v tests/sps/models/test_aff.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
[https://www.iso.org/obp/ui/#search/code/](https://www.iso.org/obp/ui/#search/code/)

2024-06-04 11:22 UTC, robertatakenaka commented on packtools/sps/models/aff.py
> +    return data
@Rossi-Luciano Melhoria para o futuro. Criar um módulo que contenha estas funções e importar onde usa. O código está duplicado

2024-06-04 11:24 UTC, robertatakenaka commented on packtools/sps/sps_versions/sps-1.9/country_codes.json
> +{
@Rossi-Luciano este arquivo tem que ficar na pasta default

2024-06-04 11:29 UTC, robertatakenaka commented on tests/sps/validation/test_aff.py
> +                    "parent_article_type": None,
@Rossi-Luciano parent_article_type está None porque está ausente no fixture ou é erro?

2024-06-04 11:38 UTC, robertatakenaka commented
@Rossi-Luciano Adiciona a validação de `aff/@id`, do tipo exist, mas o retorno é **CRITICAL** no lugar de **ERROR**. O mesmo para orgname, country e country_code.
No autor, todos os autores tem que ter xref do tipo aff, caso contrário, é CRITICAL no lugar de ERROR.

2024-06-05 17:06 UTC, Rossi-Luciano commented on packtools/sps/models/aff.py
>          inst_types = ["orgname", "orgdiv1", "orgdiv2", "original"]
OK, @robertatakenaka

2024-06-05 17:06 UTC, Rossi-Luciano commented on packtools/sps/models/aff.py
> +    return data
OK, @robertatakenaka

2024-06-05 17:06 UTC, Rossi-Luciano commented on packtools/sps/sps_versions/sps-1.9/country_codes.json
> +{
OK, @robertatakenaka

2024-06-05 17:07 UTC, Rossi-Luciano commented on tests/sps/validation/test_aff.py
> +                    "parent_article_type": None,
@robertatakenaka, alterei os testes para evidenciar `article-type` e `lang`.

2024-06-11 11:21 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
>      def validate_orgname(self):
@Rossi-Luciano adicione o parâmetro error_level=None

2024-06-11 11:22 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
> -        yield format_response(
@Rossi-Luciano manter yield

2024-06-11 11:22 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
> +        resp = format_response(
@Rossi-Luciano adicione o parâmetro error_level a format_response

2024-06-11 11:23 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
>              data=self.affiliation,
@Rossi-Luciano adicione o parâmetro error_level=error_level

2024-06-11 11:23 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
> +        yield resp
@Rossi-Luciano remover

2024-06-11 11:24 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
> +        resp = format_response(
@Rossi-Luciano fazer o mesmo para as demais validações

2024-06-11 11:26 UTC, robertatakenaka commented on packtools/sps/validation/aff.py
> +
@Rossi-Luciano fazer o mesmo

2024-06-11 11:26 UTC, robertatakenaka requested changes
modificar conforme solicitado

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
>      def validate_orgname(self):
OK, @robertatakenaka

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
> -        yield format_response(
OK, @robertatakenaka

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
> +        resp = format_response(
OK, @robertatakenaka

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
>              data=self.affiliation,
OK, @robertatakenaka

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
> +        yield resp
OK, @robertatakenaka

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
> +        resp = format_response(
OK, @robertatakenaka

2024-06-11 14:53 UTC, Rossi-Luciano commented on packtools/sps/validation/aff.py
> +
OK, @robertatakenaka

2024-06-12 11:16 UTC, merged