Chore: standardize article doi
scieloorg/packtools pull request #644
Opened 2024-07-20 22:34 UTC by Rossi-Luciano

#### O que esse PR faz?
Este Pull Request implementa uma nova funcionalidade para validação de DOIs em artigos XML. Ele adiciona métodos para:

- Verificar a existência de DOIs.
- Garantir que todos os DOIs sejam únicos.
- Validar que os DOIs estejam registrados e correspondam aos metadados esperados (título, autores).

Essas funcionalidades visam solucionar problemas relacionados à inconsistência e duplicidade de DOIs, garantindo a integridade dos dados nos artigos XML.

#### Onde a revisão poderia começar?
Sugiro iniciar pela avaliação dos testes:

- `tests/sps/models/test_article_doi_with_lang.py`
- `tests/sps/models/test_article_doi_with_lang.py`

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_article_doi.py
`
#### Algum cenário de contexto que queira dar?
NA

### Screenshots
NA

#### Quais são tickets relevantes?
NA

### Referências
NA

2024-07-24 11:47 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                title=f'{doi.get("parent")} DOI element',
@Rossi-Luciano o título deve ser padrão, sem ter variáveis. O parent é obtido do parent.

2024-07-24 11:52 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +            validation_type='exist/verification',
@Rossi-Luciano validation_type="unique"

2024-07-24 11:56 UTC, robertatakenaka commented on packtools/sps/validation/article_doi.py
> +                            obtained_authors.append(full_name)
@Rossi-Luciano não entendi. Por que está usando `seen`, um conjunto vazio, no lugar de comparar com o conteúdo de expected obtido na linha 304?

2024-07-24 12:09 UTC, robertatakenaka commented on tests/sps/validation/test_article_doi.py
>                  'validation_type': 'exist/verification',
@Rossi-Luciano validation_type só deve ser de 1 único tipo, então tem que haver 1 para exist e outra para verification (o que significa?)

2024-07-24 12:15 UTC, robertatakenaka commented on tests/sps/validation/test_article_doi.py
> +                'response': 'CRITICAL',
@Rossi-Luciano DOI não pode ser CRITICAL porque é um dado que está ou não presente no documento. Coloque CRITICAL somente se ele é um dado que só pode ser adicionado ao XML. Para entender melhor isso, imagina se o dado se apresenta ou não na página do artigo. No caso de Cuba, eles não podem ter DOI. Exemplo: `@article-type` é um dado inserido por quem marca, a partir de uma análise, não é um dado explícito no documento. Os nomes dos autores são dados presentes (ou ausentes por falha ou por característica do tipo de documento) no documento. Então, estamos obrigando, considerando CRITICAL aqueles que deveriam ser inserido manualmente. Porque aqueles dados que podem existir ou não por característica do documento, não temos como exigir.

2024-07-24 12:17 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar os questionamentos

2024-07-25 13:50 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +                            obtained_authors.append(full_name)
@robertatakenaka, o conjunto é para garantir que os nomes dos autores não sejam considerados em duplicidade, visto que estamos considerando `article` e `sub-article`.

O conteúdo de expected:
```
{
    "en": {"title": "Title in English", "doi": "10.1590/2176-4573e59270"},
    "pt": {"title": "Título em Português", "doi": "10.1590/2176-4573p59270"},
    "authors": ["Martínez-Momblán, Maria Antonia", "Colina-Torralva, Javier"],
}

```
O conteúdo de seen_authors (após a finalização do laço):
`{'Martínez-Momblán, Maria Antonia', 'Colina-Torralva, Javier'}`

2024-07-25 13:51 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_doi.py
>                  'validation_type': 'exist/verification',
OK, @robertatakenaka

2024-07-25 13:51 UTC, Rossi-Luciano commented on packtools/sps/validation/article_doi.py
> +            validation_type='exist/verification',
OK, @robertatakenaka

2024-07-28 14:07 UTC, robertatakenaka approved these changes

2024-07-28 14:08 UTC, merged