Fix: add exception handling for toc section validation in articles
scieloorg/packtools pull request #667
Opened 2024-07-31 22:40 UTC by Rossi-Luciano

#### O que esse PR faz?
Este PR adiciona tratamento de exceção na validação das seções TOC (Table of Contents) em artigos. Com essa modificação, a função agora consegue lidar com casos onde a variável `obtained` é `None`, evitando possíveis erros e garantindo que a validação seja realizada de forma robusta.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_article_toc_sections.py`

#### Algum cenário de contexto que queira dar?
NA

### Screenshots
NA

#### Quais são tickets relevantes?
TK #662 

### Referências
NA

2024-08-01 13:54 UTC, robertatakenaka commented on tests/sps/validation/test_article_toc_sections.py
> +            }
@Rossi-Luciano 
A revista pode publicar os textos em um ou mais idiomas, e por isso, há seções nos vários idiomas. No entanto, os autores não são obrigados a fornecer os textos em todos os idiomas.

Sobre o alerta só valeria se há o texto em outro idioma e só a seção estiver ausente. Caso contrário, exigir a seção e o texto em outro idioma, não faz sentido.

Se você conseguir identificar que há o sub-article, então sim pode ter o alerta. Mas a classe que está validando não está fazendo isso.

E da parte de prover a lista / o dicionário com as seções, não tem como saber previamente se o artigo terá 1 ou mais idiomas. Então, cabe a classe saber se exige ou não a presença do título da seção

2024-08-01 23:26 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_toc_sections.py
> +            }
OK, @robertatakenaka

2024-08-02 14:16 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar

2024-08-07 13:04 UTC, Rossi-Luciano commented on tests/sps/validation/test_article_toc_sections.py
> +                self.assertDictEqual(obtained[i], item)
OK @robertatakenaka

2024-08-14 12:34 UTC, robertatakenaka commented
@Rossi-Luciano este PR ainda precisa ser revisado? ficou duplicado?

2024-08-22 13:19 UTC, robertatakenaka approved these changes

2024-08-22 13:19 UTC, merged