Fix: fig validation
scieloorg/packtools pull request #674
Opened 2024-08-02 13:29 UTC by Rossi-Luciano

#### O que esse PR faz?
Este Pull Request adiciona a validação da existência de elementos `<fig> `em documentos XML, além de incluir docstrings detalhadas para a classe `FigValidation` e seus métodos. Especificamente, ele:

- Introduz a classe `FigValidation` para validar a presença de elementos `<fig>` em documentos XML.
- Implementa o método `validate_fig_existence`, que gera respostas formatadas para a presença ou ausência de elementos `<fig>.`
- Adiciona docstrings detalhadas para a classe e seus métodos, fornecendo uma descrição clara de seus atributos e funcionalidades.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
python3 -m unittest -v tests/sps/models/test_fig.py
python3 -m unittest -v tests/sps/validation/test_fig.py

#### Algum cenário de contexto que queira dar?
NA

### Screenshots
NA

#### Quais são tickets relevantes?
TK #657 

### Referências
NA

2024-08-02 14:22 UTC, robertatakenaka commented on tests/sps/models/test_fig.py
> +                    "parent_id": None,
@Rossi-Luciano Use mais de 1 figura por idioma

2024-08-02 14:24 UTC, robertatakenaka commented on tests/sps/validation/test_fig.py
> +                "title": "validation of <fig> elements",
`title="fig presence"`

2024-08-02 14:25 UTC, robertatakenaka commented on tests/sps/validation/test_fig.py
> +                "expected_value": "<fig> element",
@Rossi-Luciano Use `tostring(node)`

2024-08-02 14:29 UTC, robertatakenaka requested changes
@Rossi-Luciano Verificar os comentários

2024-08-05 15:10 UTC, Rossi-Luciano commented on tests/sps/models/test_fig.py
> +                    "parent_id": None,
OK, @robertatakenaka

2024-08-05 15:10 UTC, Rossi-Luciano commented on tests/sps/validation/test_fig.py
> +                "expected_value": "<fig> element",
OK, @robertatakenaka

2024-08-05 15:10 UTC, Rossi-Luciano commented on tests/sps/validation/test_fig.py
> +                "title": "validation of <fig> elements",
OK, @robertatakenaka

2024-08-19 14:32 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +class Figs:
@Rossi-Luciano Imagina que eu queira instanciar somente Figs de um determinado sub-article e queira os dados de sub-article? Da forma como está Figs, não tem como. Adicione a Figs `yield put_parent_context(data, lang, article_type, parent, parent_id)`

2024-08-19 14:34 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +    def article_figs(self):
@Rossi-Luciano crie métodos: 1) para obter figs somente de article; 2) para obter figs somente de sub-article

Imagina que  vai fazer a validação de parear fig1 (article) com fig1 de sub-article (translation)

2024-08-19 19:12 UTC, Rossi-Luciano commented on packtools/sps/models/fig.py
> +class Figs:
OK, @robertatakenaka

2024-08-19 19:12 UTC, Rossi-Luciano commented on packtools/sps/models/fig.py
> +    def article_figs(self):
OK, @robertatakenaka

2024-08-22 13:21 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +            data["node"] = fig
@Rossi-Luciano como node será usado?

2024-08-22 13:21 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +                yield fig
@Rossi-Luciano corrigir

2024-08-22 13:22 UTC, robertatakenaka commented on tests/sps/models/test_fig.py
> +                obtained_copy.pop("node")
@Rossi-Luciano qual é a necessidade do node?

2024-08-24 21:35 UTC, Rossi-Luciano commented on packtools/sps/models/fig.py
> +            data["node"] = fig
@robertatakenaka `node` estava sendo usado apenas para gerar o  valor de `obtained` no dicionário de resposta, achei que estava muito poluído e modifiquei o conteúdo de `obtained`, não sendo mais necessário manter o nó.

`'got_value': '<fig fig-type="None" id="f01">'`

2024-08-24 21:35 UTC, Rossi-Luciano commented on packtools/sps/models/fig.py
> +                yield fig
OK @robertatakenaka

2024-08-24 21:35 UTC, Rossi-Luciano commented on tests/sps/models/test_fig.py
> +                obtained_copy.pop("node")
Não é mais necessário @robertatakenaka

2024-08-27 13:20 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +        yield from Figs(self.xml_tree).figs()
@Rossi-Luciano troca `self.xml_tree` por `self.xml_tree.find(".")`

2024-08-27 13:22 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +        return tostring(node=self.element, doctype=None, pretty_print=True, xml_declaration=True)
@Rossi-Luciano veja o que comentei em aff

2024-08-27 13:23 UTC, robertatakenaka requested changes
@Rossi-Luciano veja o que comentei em aff, e faça a correção neste PR

2024-08-29 15:48 UTC, Rossi-Luciano commented on packtools/sps/models/fig.py
> +        yield from Figs(self.xml_tree).figs()
OK, @robertatakenaka

2024-08-29 15:49 UTC, Rossi-Luciano commented on packtools/sps/models/fig.py
> +        return tostring(node=self.element, doctype=None, pretty_print=True, xml_declaration=True)
OK, @robertatakenaka

2024-08-30 13:47 UTC, robertatakenaka commented on packtools/sps/models/fig.py
> +        self.node = node.find(".") if node.tag == "article" else node
@Rossi-Luciano corrigir

2024-08-30 13:56 UTC, robertatakenaka commented on tests/sps/models/test_fig.py
> +        for i, item in enumerate(expected):
@Rossi-Luciano se o tamanho de `obtained` está sendo testado, é aceitável usar `enumerate(obtained)`

2024-08-30 13:58 UTC, robertatakenaka requested changes
@Rossi-Luciano fazer a correção

2024-09-02 12:00 UTC, robertatakenaka approved these changes

2024-09-02 12:00 UTC, merged