Fix: xref model
scieloorg/packtools pull request #690
Opened 2024-08-21 15:17 UTC by Rossi-Luciano

#### O que esse PR faz?
Este PR implementa uma série de classes (`Xref`, `Id`, `Xrefs`, `Ids`, `ArticleXref`) para facilitar a extração de referências (`xref`) e IDs de elementos em documentos XML de artigos científicos, incluindo suporte específico para sub-artigos de tradução. Com essas classes, é possível iterar sobre todos os IDs e referências de um artigo, identificando se eles pertencem ao artigo principal ou a sub-artigos, e se esses sub-artigos são traduções ou não. Além disso, este PR inclui um conjunto abrangente de testes unitários para validar a funcionalidade implementada.

#### Onde a revisão poderia começar?
A revisão pode começar pelos seguintes arquivos:

- `article_xref.py`
- `test_article_xref.py`

#### Como este poderia ser testado manualmente?
Para testar manualmente as funcionalidades deste PR:

1. Carregue um documento XML de artigo científico que contenha referências (xref) e IDs em suas tags.
2. Utilize as classes ArticleXref, Xrefs, e Ids para extrair e iterar sobre as referências e IDs do documento.
3. Verifique se as extrações estão corretas, especialmente diferenciando entre o conteúdo do artigo principal e sub-artigos de tradução.
4. Execute os testes unitários fornecidos para garantir que todas as funcionalidades estão funcionando conforme o esperado.

#### Algum cenário de contexto que queira dar?
A modificação dessa classe tem por objetivo facilitar na validação de `@id`.

### Screenshots
NA

#### Quais são tickets relevantes?
TK #684 

### Referências
NA

2024-08-22 12:30 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +class ArticleXref:
@Rossi-Luciano identificar o contexto dos ids só faz sentido porque estamos padronizando a resposta  das validações, mas os ids são únicos no XML, então são facilmente identificáveis pelos usuários.
Já os xrefs, talvez deveria ter o contexto porque eles podem ocorrer em qualquer lugar e mais de uma vez. Mas também não é algo que deveria ser contextualizado porque eles são menções aos elementos (`@id`) e eles podem ocorrer em qualquer lugar do XML. Isso quer dizer que um xref no sub-article pode estar mencionando uma referência que ocorre em `article/back/ref-list/ref`

2024-08-22 12:31 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +
@Rossi-Luciano eu acho que você pode eliminar article_xref_rids

2024-08-22 12:32 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +    def all_xref_rids(self):
@Rossi-Luciano eu acho que você deve manter **all_xref_rids** como está

2024-08-22 12:36 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +                yield item
@Rossi-Luciano não se deve obter os itens por meio de filtro.

2024-08-22 12:36 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +    def sub_article_translation_xref_rids(self):
@Rossi-Luciano eu acho que você pode eliminar **sub_article_translation_xref_rids**

2024-08-22 12:36 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +    def sub_article_non_translation_xref_rids(self):
@Rossi-Luciano eleminar

2024-08-23 11:43 UTC, robertatakenaka requested changes
@Rossi-Luciano fazer as correções

2024-08-24 19:26 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> +            )
OK, @robertatakenaka

2024-08-24 19:26 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> +class ArticleXref:
OK, @robertatakenaka

2024-08-24 19:26 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> +    def all_xref_rids(self):
OK, @robertatakenaka

2024-08-24 19:26 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> +                yield item
OK, @robertatakenaka

2024-08-24 19:27 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> +    def sub_article_translation_xref_rids(self):
OK, @robertatakenaka

2024-08-24 19:27 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> +    def sub_article_non_translation_xref_rids(self):
OK, @robertatakenaka

2024-08-27 12:20 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> -        self.parent_id = parent_id
@Rossi-Luciano mantenha os atributos, mas os instancie usando o próprio node, ou seja:

```python
        self.lang = lang
        self.article_type = self.node.get("article-type")
        self.parent = self.node.tag
        self.parent_id = self.node.get("id")

```
porque mesmo que atualmente só há um método, o ids(), futuramente podem ser adicionados outros

2024-08-27 12:24 UTC, robertatakenaka commented on tests/sps/models/v2/test_article_xref.py
> +        self.assertEqual(len(obtained), 1)
@Rossi-Luciano nos testes em que o retorno é uma lista, sempre tenha mais de um elemento para garantir que está funcionando

2024-08-27 13:18 UTC, robertatakenaka requested changes
@Rossi-Luciano corrigir

2024-08-29 15:22 UTC, Rossi-Luciano commented on packtools/sps/models/v2/article_xref.py
> -        self.parent_id = parent_id
OK, @robertatakenaka

2024-08-30 11:44 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +        self.node = node.find(".") if node.tag == "article" else node
@Rossi-Luciano Não entendi... não seria só `self.node = node`?

2024-08-30 11:50 UTC, robertatakenaka requested changes
@Rossi-Luciano fazer a correção

2024-08-30 11:53 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +        self.xml = tostring(node=self.node, doctype=None, pretty_print=True, xml_declaration=True)
@Rossi-Luciano sugiro que isso seja um método em que o usuário possa passar os parâmetros

Teste o uso desta função, passando diferentes valores para xml_declaration, pretty_print, e avalie o resultado
```
tostring(node=self.node, doctype=None, pretty_print=True, xml_declaration=True)
```

2024-08-30 11:55 UTC, robertatakenaka commented on packtools/sps/models/v2/article_xref.py
> +        yield from Ids(self.xml_tree).ids(element_name)
```python
self.xml_tree.find(".")
```

2024-09-02 12:32 UTC, robertatakenaka approved these changes

2024-09-02 12:33 UTC, merged