Refactor: article notes (fn-group / author-notes)
scieloorg/packtools pull request #697
Opened 2024-09-09 18:40 UTC by Rossi-Luciano

#### O que esse PR faz?
Este PR implementa uma série de classes para o processamento de notas de artigos (`<fn>`, `<fn-group>`, `<author-notes>`) em documentos XML no formato SciELO PS. O objetivo é extrair, organizar e contextualizar essas notas em estruturas de dicionário que incluem informações detalhadas sobre o artigo, como tipo de artigo, idioma e identificadores. Esta implementação resolve o problema de extração manual e complexa de dados de notas, facilitando o uso programático dessas informações. Além disso, foram adicionados testes unitários abrangentes para validar o funcionamento correto de cada classe.

#### Onde a revisão poderia começar?
A revisão pode começar pelo arquivo `packtools/sps/models/v2/notes.py`, onde as classes `Fn`, `Fns`, `FnGroup`, `FnGroups`, `AuthorNote`, `AuthorNotes`, e `ArticleNotes` estão implementadas. Em seguida, revise os testes correspondentes em `tests/sps/models/v2/test_notes.py` para garantir a cobertura de funcionalidades.

#### Como este poderia ser testado manualmente?

1. Clone o repositório e navegue até o diretório do projeto.
2. Instale as dependências necessárias com `pip install -r requirements.txt`.
3. Execute os testes unitários com o comando `python3 -m unittest -v tests/sps/models/v2/test_notes.py` para verificar se todas as funcionalidades estão sendo testadas corretamente.
4. Para testes manuais, crie um arquivo XML de exemplo seguindo o padrão SciELO e utilize as classes implementadas para verificar a extração e formatação das notas.

#### Algum cenário de contexto que queira dar?
NA

### Screenshots
NA

#### Quais são tickets relevantes?
NA

### Referências
NA

2024-09-11 11:17 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +class Fn:
@Rossi-Luciano ótimo!

2024-09-11 11:24 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +
@Rossi-Luciano pode eliminar esta classe, pois não há um ganho em tê-la

2024-09-11 11:25 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.node = node
@Rossi-Luciano adicione como atributos da classe `FnGroup` os sub-elementos e atributos do elemento `fn-group`

2024-09-11 11:32 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +
@Rossi-Luciano crie um novo método que retorne todos os `fn` que não estão agrupados por `fn-group`, seus parent são o `back` (confira esta informação com a documentação SPS e/ou JATS)

2024-09-11 11:34 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +            yield data
@Rossi-Luciano consulte a documentação SPS e/ou JATS. Os métodos para AuthorNote deveriam ser: fns, corresp, ... Não tem sentido ter um método com o mesmo nome da classe.

2024-09-11 11:35 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +                "corresp_label": process_subtags(author_note.find("corresp/label")),
@Rossi-Luciano isso deveria ser método de AuthorNote

2024-09-11 11:38 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +
@Rossi-Luciano observação: mesmo que o grupo de notas não tenham o fn-group, vc pode considerar "grupo", só não terão os dados de fn-group-type, e demais elementos encontrados no fn-group

2024-09-11 20:46 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> -class Fn:
@Rossi-Luciano por favor, modifica as linhas que estavam erradas. Desta forma a revisão ficou difícil

2024-09-11 20:59 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +class NoteGroup:
@Rossi-Luciano Troque `NoteGroup` por `AbstractNoteGroup` ou `BaseNoteGroup`

2024-09-11 20:59 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.parent = parent
@Rossi-Luciano quem é node quem é parent?

2024-09-11 21:04 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +    def _get_note_class(self):
@Rossi-Luciano não parece boa solução

2024-09-11 21:07 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +            data["fn_parent"] = self.parent
@Rossi-Luciano não parece que faz sentido...

2024-09-11 21:07 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        note_class = self._get_note_class
@Rossi-Luciano remover esta linha

2024-09-11 21:11 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, node, node_tag):
@Rossi-Luciano Troca `def __init__(self, node, node_tag):` por `def __init__(self, node, node_tag, NoteGroupClass):`

2024-09-11 21:12 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.node = node
@Rossi-Luciano adiciona: `self.NoteGroupClass = NoteGroupClass`

2024-09-11 21:13 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +            data = note_class(group).data
Trocar `data = note_class(group).data` por `data = self.NodeGroupClass(group).data`

2024-09-11 21:24 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.node_tag = node_tag
Trocar por self.note_tag = note_tag

2024-09-11 21:25 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.parent = node.tag
Troca por self.parent = parent_node.tag

2024-09-11 21:28 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        # author note node
@Rossi-Luciano comentário incorreto. O correto é: `# node =  article ou sub-article. Adote nomes mais significativos ou comentários adequados. A primeira sugestão é melhor.

2024-09-11 21:29 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        # footnote group node
@Rossi-Luciano comentário incorreto. O correto é: `# node =  article ou sub-article`. Adote nomes mais significativos ou comentários adequados. A primeira sugestão é melhor.

2024-09-12 13:43 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
@Rossi-Luciano não é óbvio quem é fn_container_node, fn_container_tag_name

2024-09-12 13:43 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +            data["fn_parent"] = self.fn_container_tag_name
@Rossi-Luciano fn_parent é mais óbvio

2024-09-12 13:44 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, article_or_sub_article_node, fn_container_tag_name, NoteGroupClass):
@Rossi-Luciano fn_parent_tag_name é mais claro que fn_container_tag_name

2024-09-12 13:47 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.has_bold = bool(self.fn_node.findtext("bold"))
@Rossi-Luciano já estava ótimo. Node no contexto do Elemento, é claramente o nó do elemento

2024-09-12 13:51 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, fn_container_node, fn_container_tag_name):
@Rossi-Luciano não está claro quem é fn_container_node, fn_container_tag_name

2024-09-12 13:56 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, fn_container_node, fn_container_tag_name):
O que acha de `fn_parent_node` e `fn_parent_tag`?

2024-09-12 13:57 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, fn_container_node, fn_container_tag_name):
@Rossi-Luciano remover fn_container_tag_name

2024-09-12 14:00 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.has_bold = bool(self.fn_node.findtext("bold"))
@Rossi-Luciano Trocar `self.has_bold = bool(self.fn_node.findtext("bold"))` por `self.bold = self.fn_node.findtext("bold")

2024-09-12 14:01 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        super().__init__(author_notes_node, "author-notes")
Remover as linhas 88 e 89

2024-09-12 14:01 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        super().__init__(fn_group_node, "fn-group")
@Rossi-Luciano remover as linhas 62 e 63

2024-09-12 14:04 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, fn_container_node, fn_container_tag_name):
@Rossi-Luciano Mudar fn_container_node para node (se o nó se refere ao nó do classe que representa pode se chamar node). Mas não dá para usar node para representar article ou sub-article fora do contexto deles

2024-09-12 14:09 UTC, robertatakenaka requested changes
@Rossi-Luciano corrigir somente aquilo que foi solicitado

2024-09-12 14:18 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
OK @robertatakenaka 
`container` foi substituído por `parent`

2024-09-12 14:18 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +            data["fn_parent"] = self.fn_container_tag_name
OK, @robertatakenaka

2024-09-12 14:18 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +    def __init__(self, article_or_sub_article_node, fn_container_tag_name, NoteGroupClass):
OK, @robertatakenaka

2024-09-12 14:18 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +        self.has_bold = bool(self.fn_node.findtext("bold"))
OK, @robertatakenaka
Retornei ao que era

2024-09-12 14:19 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +        self.fn_container_tag_name = fn_container_tag_name
Genial @robertatakenaka

2024-09-12 14:19 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +        super().__init__(fn_group_node, "fn-group")
OK, @robertatakenaka

2024-09-12 16:40 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +            data["fn_parent"] = self.fn_parent_tag_name
@Rossi-Luciano usar self.fn_parent_node.tag

2024-09-12 16:40 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.fn_parent_tag_name = fn_parent_node.tag
@Rossi-Luciano remover `self.fn_parent_tag_name = fn_parent_node.tag`

2024-09-12 16:41 UTC, robertatakenaka commented on packtools/sps/models/v2/notes.py
> +        self.has_bold = bool(self.node.findtext("bold"))
@Rossi-Luciano Trocar has_bold por `self.bold = self.node.findtext("bold")`

2024-09-12 17:45 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +        self.has_bold = bool(self.node.findtext("bold"))
OK, @robertatakenaka

2024-09-12 17:45 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +        self.fn_parent_tag_name = fn_parent_node.tag
OK, @robertatakenaka

2024-09-12 17:45 UTC, Rossi-Luciano commented on packtools/sps/models/v2/notes.py
> +            data["fn_parent"] = self.fn_parent_tag_name
OK, @robertatakenaka

2024-09-13 11:48 UTC, robertatakenaka approved these changes

2024-09-13 11:49 UTC, merged