Feat: realated article validation
scieloorg/packtools pull request #698
Opened 2024-09-12 17:35 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona validações para `related_article`.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_related_articles.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-09-13 11:41 UTC, robertatakenaka commented
@Rossi-Luciano revisado e aprovado até o commit 2

2024-09-13 14:02 UTC, robertatakenaka commented on packtools/sps/validation/related_articles.py
> +from packtools.sps.models import article_and_subarticles, article_dates
@Rossi-Luciano se não me engano, foi feita a versão v2 deste modelo...

2024-09-13 14:09 UTC, robertatakenaka commented on packtools/sps/validation/related_articles.py
> +                title='Related article type validation',
@Rossi-Luciano o valor de title não condiz com o nome do método

2024-09-13 14:11 UTC, robertatakenaka commented on packtools/sps/validation/related_articles.py
> +        for related_article in self.related_articles:
@Rossi-Luciano todos os related article tem obrigatoriamente que ter uma data relacionadoa no histórico?

2024-09-13 14:14 UTC, robertatakenaka commented on tests/sps/validation/test_related_articles.py
> +    def test_related_articles_attribute_validation(self):
@Rossi-Luciano o nome deste teste está muito genérico. O que de fato ele está testando? Deveria ser algo como: `test_related_article_type_xxx_exige_que_exista_a_data_yyy_no_historico`

2024-09-13 14:16 UTC, robertatakenaka commented on tests/sps/validation/test_related_articles.py
> +                'title': 'Related article type validation',
@Rossi-Luciano title não condiz com o que está sendo validado.

2024-09-13 14:16 UTC, robertatakenaka commented on tests/sps/validation/test_related_articles.py
> +                'title': 'Related article type validation',
@Rossi-Luciano title não condiz com o que está sendo validado.

2024-09-13 14:16 UTC, robertatakenaka commented on tests/sps/validation/test_related_articles.py
> +                'title': 'Related article type validation',
@Rossi-Luciano title não condiz com o que está sendo validado.

2024-09-13 14:18 UTC, robertatakenaka commented on tests/sps/validation/test_related_articles.py
> +            <year>2012</year>
@Rossi-Luciano eu acho que está errado. Esta data é esperada no XML do artigo corrigido e não no XML da errata

2024-09-13 14:18 UTC, robertatakenaka commented on tests/sps/validation/test_related_articles.py
> +            <year>2012</year>
@Rossi-Luciano vc já fez esta validação na classe que valida errata. Considere o que já foi feito

2024-09-13 14:20 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar comentários

2024-09-13 14:24 UTC, Rossi-Luciano commented on packtools/sps/validation/related_articles.py
> +from packtools.sps.models import article_and_subarticles, article_dates
@robertatakenaka para esse caso o módulo foi renomeado de `dates` para `article_dates` e não está em v2 mas é o módulo novo.

2024-09-16 10:52 UTC, robertatakenaka commented on packtools/sps/validation/related_articles.py
> -    def related_articles_matches_history_date_validation(self, correspondence_list=None, error_level="ERROR"):
@Rossi-Luciano isso está sendo atendido em outra classe? Era um questionamento

2024-09-16 10:54 UTC, robertatakenaka commented on packtools/sps/validation/related_articles.py
> +                        title='Related article attributes validation',
@Rossi-Luciano gostaria que o título não tivesse validation para deixar mais curto, pois tudo é validation. Em title deixe mais específico que aspecto está sendo validado. Neste caso, use f'Related article {attrib}'

2024-09-22 19:46 UTC, Rossi-Luciano commented on packtools/sps/validation/related_articles.py
> +                title='Related article type validation',
OK, @robertatakenaka

2024-09-22 19:46 UTC, Rossi-Luciano commented on packtools/sps/validation/related_articles.py
> +        for related_article in self.related_articles:
OK, @robertatakenaka

2024-09-22 19:46 UTC, Rossi-Luciano commented on tests/sps/validation/test_related_articles.py
> +    def test_related_articles_attribute_validation(self):
OK, @robertatakenaka

2024-09-22 19:46 UTC, Rossi-Luciano commented on tests/sps/validation/test_related_articles.py
> +                'title': 'Related article type validation',
OK, @robertatakenaka

2024-09-22 19:46 UTC, Rossi-Luciano commented on tests/sps/validation/test_related_articles.py
> +                'title': 'Related article type validation',
OK, @robertatakenaka

2024-09-22 19:46 UTC, Rossi-Luciano commented on tests/sps/validation/test_related_articles.py
> +                'title': 'Related article type validation',
OK, @robertatakenaka

2024-09-22 19:46 UTC, Rossi-Luciano commented on tests/sps/validation/test_related_articles.py
> +            <year>2012</year>
OK, @robertatakenaka

2024-09-22 19:47 UTC, Rossi-Luciano commented on packtools/sps/validation/related_articles.py
> -    def related_articles_matches_history_date_validation(self, correspondence_list=None, error_level="ERROR"):
OK, @robertatakenaka

2024-09-22 19:47 UTC, Rossi-Luciano commented on packtools/sps/validation/related_articles.py
> +                        title='Related article attributes validation',
OK, @robertatakenaka

2024-09-23 11:14 UTC, robertatakenaka commented on packtools/sps/validation/errata.py
> +    ]
@Rossi-Luciano será que o melhor não seria ter o filtro e iterar em todos os related-article? Desta forma não está escondendo possíveis defeitos no XML ao ignorar os related-article de tipo inesperados?

2024-09-23 11:18 UTC, robertatakenaka commented on packtools/sps/validation/errata.py
> +        if history_date_count < related_article_count:
@Rossi-Luciano não acho boa a abordagem de contagem. A abordagem a ser adotada deveria ser pareada. Porque o objetivo não é saber se a quantidade bate, mas qual é o item que tem a data faltando. E vice versa, se há a data no histórico e não há o related-article.

2024-09-24 13:30 UTC, Rossi-Luciano commented
@robertatakenaka mudei a abordagem da validação.

2024-09-30 12:50 UTC, robertatakenaka commented on packtools/sps/validation/errata.py
> +        self.related_articles = list(RelatedArticles(xml_tree).related_articles())
@Rossi-Luciano aqui está sendo recuperado todos os related_articles. Em RelatedArticles, crie método para filtrar somente os related_articles com os quais deseja trabalhar, no lugar de criar em RelatedArticlesValidation o método get_related_article_types_by_article_type

2024-12-16 18:44 UTC, robertatakenaka commented on packtools/sps/models/v2/related_articles.py
> +def remove_namespaces(xml_string):
@Rossi-Luciano qual a necessidade?

2025-01-22 12:31 UTC, robertatakenaka commented
Resolvido por #824

2025-01-22 12:31 UTC, closed without merging