Feat: text between comment and ext link
scieloorg/packtools pull request #705
Opened 2024-09-16 15:27 UTC by Rossi-Luciano

#### O que esse PR faz?
Este PR adiciona funcionalidades para validar a presença de texto entre as tags `<comment>` e `<ext-link>` dentro de elementos `<element-citation>` em documentos XML. As principais alterações introduzidas são:

1. Função `get_comment_text`:

- Implementa uma lógica para localizar elementos `<comment>` que contêm `<ext-link>`.
- Extrai o texto completo do `<comment>` e verifica se há texto presente antes do `<ext-link>`.
- Retorna uma lista de dicionários contendo o texto completo do `<comment>`, o texto encontrado entre `<comment>` e `<ext-link>`, e o texto dentro do `<ext-link>`.

2. Função `validate_text_between_comment_and_ext_link`:

- Valida se existe texto entre `<comment>` e `<ext-link>`.
- Gera uma resposta de validação quando o texto está ausente, indicando que deve haver um texto entre `<comment>` e `<ext-link>`.
- Produz uma mensagem de erro com detalhes sobre a ausência do texto, oferecendo um conselho para adicionar o texto necessário entre os elementos.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?

- Carregue um XML de artigo que contenha elementos `<element-citation>` com `<comment>` e `<ext-link>`.
- Execute a função `get_comment_text` para verificar se ela extrai corretamente o texto entre `<comment>` e `<ext-link>`.
- Utilize a função `validate_text_between_comment_and_ext_link` para validar se o texto entre `<comment>` e `<ext-link>` existe.
- Confirme que um erro é gerado se o texto estiver ausente, e que a mensagem sugere a inclusão de um texto adequado.
 
#### Algum cenário de contexto que queira dar?
NA

### Screenshots
NA

#### Quais são tickets relevantes?
NA

### Referências
NA

2024-09-16 17:14 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +def get_comment_text(node):
@Rossi-Luciano idealmente todas estas funções, deveriam ser atributos / métodos da classe de uma class ArticleReference, instanciada com o node (ref)

2024-09-16 17:20 UTC, robertatakenaka commented on packtools/sps/validation/article_citations.py
> +    def validate_text_between_comment_and_ext_link(self, error_level="ERROR"):
@Rossi-Luciano 

> Referência comment: Validar comment em ref quando tiver uma ext-link. Acusar erro quando houver comment sem informação textual que anteceda o ext-link
> Acusar Erro Fatal
> O uso de **comment só se aplica quando há algum texto que antecede o link**. 
> Podemos ter em ref: <comment>Disponível em: <ext-link>[http://www…](about:blank)
> Podemos ter em ref: <ext-link>[http://www…](about:blank)
> Não podemos ter: <comment><ext-link>[http://www…](about:blank)

Dito isso, o advice **não** é para pedir para que um texto seja inserido. O produtor de XML **não pode adulterar** o texto original. O advice deve ser não usar o elemento comment já que não há um texto que preceda o link.

2024-09-16 17:25 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +def get_comment_text(node):
@Rossi-Luciano adicione uma função ou método que obtenha o texto da seguinte forma:
```python
def get_text_before_extlink(ref_node):
    extlink_node = ref_node.find(".//ext-link")
    if extlink_node is not None:
        previous = extlink_node.getprevious()
        return previous.tail
```
Se existir este texto, o advice deve ser que deve ser inserido um elemento comment que envolva o texto + o ext-link.

2024-09-16 17:26 UTC, robertatakenaka requested changes
@Rossi-Luciano corrigir e completar as validações

2024-09-18 17:21 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +                    ("text_before_extlink", ref.get_text_before_extlink())
@Rossi-Luciano cria um método chamado data em ArticleReference

2024-09-18 17:23 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +                }
@Rossi-Luciano deste modo, não está retornando o ext_link_text

2024-09-18 17:30 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +                }
O correto seria:
```python
    def get_extlink_and_comment_content(self):
        ext_link = self.ref.find("./element-citation//ext-link")
        if ext_link is not None:
            text_between = None
            full_comment = None
            comment = self.ref.find("./element-citation/comment")
            if comment is not None:
                text_between = comment.text
                full_comment = process_subtags(comment) or None

            return {
                'full_comment': full_comment,
                'text_between': text_between,
                'ext_link_text': process_subtags(ext_link),
                'text_before': self.get_text_before_ext_link(),
            }
```

2024-09-18 17:31 UTC, robertatakenaka requested changes
@Rossi-Luciano Realizar as correções

2024-09-18 17:41 UTC, robertatakenaka commented on packtools/sps/validation/article_citations.py
> +        if not comment:
@Rossi-Luciano o fato de não existir comente, não pode impedir de seguir com a validação. A presença de text_before_extlink tem que ser avaliada

2024-09-18 17:43 UTC, robertatakenaka commented on packtools/sps/validation/article_citations.py
> +    def validate_text_between_comment_and_ext_link(self, error_level="ERROR"):
@Rossi-Luciano no lugar de 'validate_text_between_comment_and_ext_link' use 'validate_comment_is_required
_or_not'

2024-09-18 17:49 UTC, robertatakenaka commented on packtools/sps/validation/article_citations.py
> +                    title="text between comment and ext-link",
@Rossi-Luciano corrigir o title

2024-09-19 11:12 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +        return text
@Rossi-Luciano Não adulterar o valor

2024-09-19 11:12 UTC, robertatakenaka commented on packtools/sps/models/article_citations.py
> +        collabs = self.ref.xpath("./element-citation/person-group//collab")
@Rossi-Luciano não é necessário criar a variável collabs

2024-09-19 13:53 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +def get_comment_text(node):
OK, @robertatakenaka

2024-09-19 13:53 UTC, Rossi-Luciano commented on packtools/sps/validation/article_citations.py
> +    def validate_text_between_comment_and_ext_link(self, error_level="ERROR"):
OK, @robertatakenaka

2024-09-19 13:53 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +                    ("text_before_extlink", ref.get_text_before_extlink())
OK, @robertatakenaka

2024-09-19 13:53 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +                }
OK, @robertatakenaka

2024-09-19 13:54 UTC, Rossi-Luciano commented on packtools/sps/validation/article_citations.py
> +        if not comment:
OK, @robertatakenaka

2024-09-19 13:54 UTC, Rossi-Luciano commented on packtools/sps/validation/article_citations.py
> +                    title="text between comment and ext-link",
OK, @robertatakenaka

2024-09-19 13:54 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +        return text
OK, @robertatakenaka

2024-09-19 13:54 UTC, Rossi-Luciano commented on packtools/sps/models/article_citations.py
> +        collabs = self.ref.xpath("./element-citation/person-group//collab")
OK, @robertatakenaka

2024-09-20 12:09 UTC, robertatakenaka approved these changes

2024-09-20 12:09 UTC, merged