Fix: article lang validation
scieloorg/packtools pull request #713
Opened 2024-10-06 23:36 UTC by Rossi-Luciano

#### O que esse PR faz?
Altera a iteração sobre os títulos para o artigo e sub-artigos.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
`python3 -m unittest -v tests/sps/validation/test_article_lang.py
`
#### Algum cenário de contexto que queira dar?
NA

### Screenshots
NA

#### Quais são tickets relevantes?
TK #712 

### Referências
NA.

2024-10-10 11:38 UTC, robertatakenaka commented on packtools/sps/validation/article_lang.py
> +        for article_and_subarticles_dict in article_and_subarticles_list:
@Rossi-Luciano eu tinha comentado que eu estava enganada. Tem que juntas os idiomas de todos: dos resumos, dos títulos do artigo, das palavras chaves. E iterar por eles.

2024-12-03 16:49 UTC, robertatakenaka commented on packtools/sps/validation/article_lang.py
> +        for item in self.article_and_subarticles.data:
@Rossi-Luciano o objetivo desta validação é confirmar que todos os metadados tenham os correspondentes em todos os idiomas. O texto completo não tem todos os idiomas (article e sub-article). É possível que exista somente article e dentro de há os metadados podem em outros idiomas. Então, iterar pelo article e sub-article não soluciona. Use a soma de todos os idiomas de todos os metadados no lugar dos idiomas article e sub-article.

2024-12-03 16:50 UTC, robertatakenaka requested changes
@Rossi-Luciano corrigir

2024-12-04 15:33 UTC, Rossi-Luciano commented on packtools/sps/validation/article_lang.py
> +        for item in self.article_and_subarticles.data:
OK, @robertatakenaka

2024-12-16 18:35 UTC, robertatakenaka commented on packtools/sps/validation/article_lang.py
> +        languages = {self.xml_tree.attrib.get(XML_NS)} if self.xml_tree.attrib.get(XML_NS) else set()
@Rossi-Luciano o teste foi feito com lxml ou com a biblioteca nativa?

2024-12-16 18:38 UTC, robertatakenaka submitted a review, later dismissed

2024-12-16 18:38 UTC, merged