Feat: build article meta elements
scieloorg/packtools pull request #723
Opened 2024-10-22 15:04 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona função para a criação do elemento `article-meta` no formato xml.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Sugiro verificar os testes automatizados: 

`python3 -m unittest -v tests/sps/formats/sps_xml/test_article_meta.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-11-07 21:40 UTC, robertatakenaka commented on packtools/sps/formats/sps_xml/article_meta.py
> +def build_article_meta(data):
@Rossi-Luciano adicionar `, node`

Tem que adicionar abstract, trans-abstract ... há outros elementos em article-meta

2024-11-07 21:40 UTC, robertatakenaka requested changes
@Rossi-Luciano adicionar os _nodes_

2024-11-10 20:34 UTC, Rossi-Luciano commented on packtools/sps/formats/sps_xml/article_meta.py
> +def build_article_meta(data):
OK, @robertatakenaka

2024-11-11 11:54 UTC, robertatakenaka commented on packtools/sps/formats/sps_xml/article_meta.py
> +                    article_meta.append(elem)
@Rossi-Luciano você tentou usar o article_meta.extent(elem) no lugar de usar for + append?

2024-11-11 11:56 UTC, robertatakenaka approved these changes

2024-11-11 11:56 UTC, merged