Feat: build fig element
scieloorg/packtools pull request #748
Opened 2024-11-04 15:19 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona função para criar o elemento `fig` no formato xml.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Sugiro avaliar os testes.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-11-07 11:50 UTC, robertatakenaka commented on packtools/sps/formats/sps_xml/fig.py
> +    if xlink := data.get("graphic-xlink"):
@Rossi-Luciano considerar 3 graphics: padrão (standard), miniatura (thumbnail), alta definição (hd)

2024-11-07 11:51 UTC, robertatakenaka requested changes
@Rossi-Luciano acrescentar alternatives

2024-11-12 13:55 UTC, Rossi-Luciano commented on packtools/sps/formats/sps_xml/fig.py
> +    if xlink := data.get("graphic-xlink"):
@robertatakenaka, aqui será considerado somente um `graphic` conforme sua orientação.

2024-11-15 14:59 UTC, Rossi-Luciano commented
@robertatakenaka de acordo com a documentação, não há `alternatives` para `fig`. está correto?

2024-11-19 13:50 UTC, robertatakenaka commented on packtools/sps/formats/sps_xml/fig.py
> +            - "graphic-xlink" (str): Optional. The xlink for a graphic element.
@Rossi-Luciano mantenha um padrão entre. as coisas parecidas. Em table-wrap e disp-formula, você usou `graphic`, então aqui também deveria ser `graphic` no lugar de `graphic-xlink`.

2024-11-19 14:24 UTC, Rossi-Luciano commented on packtools/sps/formats/sps_xml/fig.py
> +            - "graphic-xlink" (str): Optional. The xlink for a graphic element.
OK, @robertatakenaka

2024-11-21 11:51 UTC, robertatakenaka approved these changes

2024-11-21 11:51 UTC, merged