Feat: build table wrap element
scieloorg/packtools pull request #749
Opened 2024-11-05 16:12 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona função para gerar o elemento `table-wrap` no formato xml.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Sugiro avaliar os testes:

`python3 -m unittest -v tests/sps/formats/sps_xml/test_table_wrap.py
`
#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-11-07 11:56 UTC, robertatakenaka commented on packtools/sps/formats/sps_xml/table_wrap.py
> +
@Rossi-Luciano adicionar alternatives

2024-11-07 11:56 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar comentários

2024-11-12 17:48 UTC, Rossi-Luciano commented on packtools/sps/formats/sps_xml/table_wrap.py
> +
OK, @robertatakenaka

2024-11-19 13:55 UTC, robertatakenaka approved these changes

2024-11-19 13:55 UTC, merged