Refactor: formula validation
scieloorg/packtools pull request #767
Opened 2024-11-27 14:09 UTC by Rossi-Luciano

#### O que esse PR faz?
Refatora a validação de fórmulas.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
Sugiro avaliar os testes:

`python3 -m unittest -v tests/sps/validation/test_formula.py`

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
NA.

### Referências
NA.

2024-12-03 16:03 UTC, robertatakenaka commented on packtools/sps/validation/formula.py
> +class FormulaValidation:
@Rossi-Luciano falta validação de alternatives, tex-math, mathml, label

2024-12-03 16:03 UTC, robertatakenaka commented on packtools/sps/validation/formula.py
> +                title="formula",
@Rossi-Luciano use o nome do elemento `disp-formula` no lugar de formula em todos os textos

2024-12-03 16:05 UTC, robertatakenaka commented on packtools/sps/validation/formula.py
> +        if not self.elements_by_language:
@Rossi-Luciano tem necessidade de classificar por idioma?

2024-12-03 16:05 UTC, robertatakenaka commented on packtools/sps/validation_rules/formula_rules.json
> +        "id_error_level": "CRITICAL"
@Rossi-Luciano label, alternatives, tex-math, mml

2024-12-03 16:12 UTC, robertatakenaka requested changes
@Rossi-Luciano corrigir

2024-12-16 18:07 UTC, robertatakenaka requested changes
@Rossi-Luciano realizar as correções

2024-12-16 18:39 UTC, robertatakenaka commented on packtools/sps/models/formula.py
> +        return [
@Rossi-Luciano retornar 1 item apenas, não usar lista

2024-12-16 18:39 UTC, robertatakenaka commented on packtools/sps/models/formula.py
> +    def tex_math(self):
@Rossi-Luciano retornar 1 item apenas, não usar lista

2024-12-16 18:39 UTC, robertatakenaka commented on packtools/sps/models/formula.py
> +    def graphic(self):
@Rossi-Luciano retornar 1 item apenas, não usar lista

2024-12-16 23:02 UTC, Rossi-Luciano commented on packtools/sps/models/formula.py
> +            for item in node.xpath(".//disp-formula | .//inline-formula"):
OK, @robertatakenaka

2024-12-16 23:03 UTC, Rossi-Luciano commented on packtools/sps/models/formula.py
> +        return [
OK, @robertatakenaka

2024-12-16 23:03 UTC, Rossi-Luciano commented on packtools/sps/models/formula.py
> +    def tex_math(self):
OK, @robertatakenaka

2024-12-16 23:03 UTC, Rossi-Luciano commented on packtools/sps/models/formula.py
> +    def graphic(self):
OK, @robertatakenaka

2024-12-27 13:37 UTC, merged